//! One-way export of native Syscribe elements to SysML v2 textual notation
//! (`ADR-SYS-SYSMLV2-002`, `REQ-TRS-SYSMLV2-037`..`-042`).
//!
//! This is the *only* writer in the SysMLv2 subsystem and it is export-only:
//! ingestion (`ADR-SYS-SYSMLV2-001`) stays read-only and nothing here is ever
//! read back as the same Syscribe elements. The writer is a pure function of
//! the loaded element graph — it never touches disk — so the CLI
//! (`syscribe export-sysml`) and the MCP `export_sysml` tool share it.
//!
//! Shape: the qualified-name tree becomes nested `package`s; a definition or
//! usage whose qname parent is itself a definition/usage nests in that
//! parent's body. Elements of an unsupported type are replaced by a
//! `// skipped: <qname> (<type>)` comment and counted in [`ExportReport`].

use std::collections::{BTreeMap, HashMap};

use crate::element::{ElementType, RawElement};

/// Failure modes of [`export_sysml`].
#[derive(Debug, thiserror::Error)]
pub enum ExportError {
    /// The requested scope names no element (or implicit package) in the model.
    #[error("no element or package '{0}' in the model")]
    UnknownScope(String),
}

/// Exported/skipped accounting (`REQ-TRS-SYSMLV2-040`).
#[derive(Debug, Clone, Default)]
pub struct ExportReport {
    /// Rendered elements per Syscribe element type name.
    pub exported: BTreeMap<String, usize>,
    /// Skipped (unsupported) elements per Syscribe element type name.
    pub skipped: BTreeMap<String, usize>,
    /// `(qname, type)` of every skipped element, in output order.
    pub skipped_elements: Vec<(String, String)>,
}

impl ExportReport {
    pub fn exported_total(&self) -> usize {
        self.exported.values().sum()
    }
    pub fn skipped_total(&self) -> usize {
        self.skipped.values().sum()
    }
    /// One-line summary used by the CLI's stderr note.
    pub fn summary_line(&self) -> String {
        let fmt = |m: &BTreeMap<String, usize>| {
            if m.is_empty() {
                "none".to_string()
            } else {
                m.iter().map(|(k, n)| format!("{k} x{n}")).collect::<Vec<_>>().join(", ")
            }
        };
        format!(
            "exported {} element(s) ({}); skipped {} ({})",
            self.exported_total(),
            fmt(&self.exported),
            self.skipped_total(),
            fmt(&self.skipped)
        )
    }
}

/// Result of an export.
#[derive(Debug, Clone)]
pub struct SysmlExport {
    /// The whole export as one document, ending in a `//` summary block.
    pub text: String,
    /// One `(top-level name, text)` per top-level node, for directory output.
    pub parts: Vec<(String, String)>,
    pub report: ExportReport,
}

const HEADER: &str = "// Generated by `syscribe export-sysml` (ADR-SYS-SYSMLV2-002). One-way export: edits here are never read back.\n";

/// SysML v2 reserved words that cannot be used as a bare name.
const RESERVED: &[&str] = &[
    "abstract", "accept", "action", "actor", "after", "alias", "all", "allocate", "allocation", "analysis",
    "and", "as", "assert", "assign", "assume", "at", "attribute", "bind", "binding", "by", "calc",
    "case", "comment", "concern", "connect", "connection", "constraint", "decide", "def", "default",
    "defined", "dependency", "derived", "do", "doc", "else", "end", "entry", "enum", "event", "exhibit",
    "exit", "expose", "false", "filter", "first", "flow", "for", "fork", "frame", "from", "hastype",
    "if", "implies", "import", "in", "include", "individual", "inout", "interface", "istype", "item",
    "join", "language", "loop", "merge", "message", "meta", "metadata", "nonunique", "not", "null",
    "objective", "occurrence", "of", "or", "ordered", "out", "package", "parallel", "part", "perform",
    "port", "private", "protected", "public", "readonly", "redefines", "ref", "references", "render",
    "rendering", "rep", "require", "requirement", "return", "satisfy", "send", "snapshot", "specializes",
    "stakeholder", "state", "subject", "subsets", "succession", "then", "timeslice", "to", "transition",
    "true", "until", "use", "variant", "variation", "verification", "verify", "via", "view", "viewpoint",
    "when", "while", "xor",
];

/// `REQ-TRS-SYSMLV2-039`: a bare SysML identifier, or `'quoted'` when it is not
/// a basic name or is a reserved word. `\` and `'` are escaped.
pub fn sysml_ident(name: &str) -> String {
    let mut chars = name.chars();
    let basic = chars.next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if basic && !RESERVED.contains(&name) {
        return name.to_string();
    }
    let mut out = String::from("'");
    for c in name.chars() {
        if c == '\\' || c == '\'' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('\'');
    out
}

/// A `::`-qualified reference with every segment rendered by [`sysml_ident`].
fn qualified(path: &str) -> String {
    path.split("::").map(sysml_ident).collect::<Vec<_>>().join("::")
}

/// How an element type renders: keyword, whether it is a definition.
fn kind_of(t: &ElementType) -> Option<(&'static str, bool)> {
    use ElementType as T;
    Some(match t {
        T::Package => ("package", false),
        T::PartDef => ("part", true),
        T::Part => ("part", false),
        T::PortDef => ("port", true),
        T::Port => ("port", false),
        T::AttributeDef => ("attribute", true),
        T::Attribute => ("attribute", false),
        T::ConnectionDef => ("connection", true),
        T::Connection => ("connection", false),
        T::InterfaceDef => ("interface", true),
        T::Interface => ("interface", false),
        T::ItemDef => ("item", true),
        T::Item => ("item", false),
        T::RequirementDef => ("requirement", true),
        T::Requirement => ("requirement", false),
        T::ActionDef => ("action", true),
        T::Action => ("action", false),
        T::StateDef => ("state", true),
        T::State => ("state", false),
        T::ConstraintDef => ("constraint", true),
        T::Constraint => ("constraint", false),
        T::CalculationDef => ("calc", true),
        T::Calculation => ("calc", false),
        _ => return None,
    })
}

#[derive(Default)]
struct Node<'a> {
    elem: Option<&'a RawElement>,
    children: BTreeMap<String, Node<'a>>,
}

fn type_name(e: &RawElement) -> String {
    e.frontmatter.element_type.as_ref().map_or("Unknown", |t| t.name()).to_string()
}

struct Writer {
    /// stable id -> qname, for turning `REQ-*` references into qualified names.
    ids: HashMap<String, String>,
    report: ExportReport,
}

/// Export `elements` (the walked graph) — all of it, or the subtree of `scope`.
pub fn export_sysml(elements: &[RawElement], scope: Option<&str>) -> Result<SysmlExport, ExportError> {
    let mut root: Node = Node::default();
    let mut ids = HashMap::new();
    for e in elements {
        if e.qualified_name.is_empty() {
            continue;
        }
        if let Some(id) = &e.frontmatter.id {
            ids.insert(id.clone(), e.qualified_name.clone());
        }
        let mut cur = &mut root;
        for seg in e.qualified_name.split("::") {
            cur = cur.children.entry(seg.to_string()).or_default();
        }
        cur.elem = Some(e);
    }

    let mut w = Writer { ids, report: ExportReport::default() };

    let tops: Vec<(String, String, &Node)> = match scope.map(str::trim).filter(|s| !s.is_empty()) {
        Some(sc) => {
            let mut cur = &root;
            let mut last = "";
            for seg in sc.split("::") {
                cur = cur.children.get(seg).ok_or_else(|| ExportError::UnknownScope(sc.to_string()))?;
                last = seg;
            }
            vec![(last.to_string(), sc.to_string(), cur)]
        }
        None => root.children.iter().map(|(n, nd)| (n.clone(), n.clone(), nd)).collect(),
    };

    let mut parts = Vec::new();
    let mut text = String::from(HEADER);
    for (name, qname, node) in tops {
        let mut buf = String::new();
        let mut sats = Vec::new();
        w.render_node(&name, &qname, node, 0, &mut buf, &mut sats);
        for line in sats {
            buf.push_str(&line);
        }
        let mut part = String::from(HEADER);
        part.push('\n');
        part.push_str(&buf);
        parts.push((name, part));
        text.push('\n');
        text.push_str(&buf);
    }

    // Trailing summary block (REQ-TRS-SYSMLV2-040).
    text.push('\n');
    text.push_str("// ---- export summary ----\n");
    text.push_str(&format!("// {}\n", w.report.summary_line()));

    Ok(SysmlExport { text, parts, report: w.report })
}

impl Writer {
    fn reference(&self, raw: &str) -> String {
        match self.ids.get(raw) {
            Some(q) => qualified(q),
            None => qualified(raw),
        }
    }

    /// `sats` collects the real `satisfy <req> by <subject>;` statements
    /// (`REQ-TRS-SYSMLV2-051`) owed to the nearest enclosing package body; a
    /// package-like node drains its own buffer into its body.
    fn render_node(
        &mut self,
        name: &str,
        qname: &str,
        node: &Node<'_>,
        depth: usize,
        out: &mut String,
        sats: &mut Vec<String>,
    ) {
        let pad = "    ".repeat(depth);
        let Some(elem) = node.elem else {
            // Implicit intermediate namespace -> package (structure, not counted).
            out.push_str(&format!("{pad}package {} {{\n", sysml_ident(name)));
            let mut own = Vec::new();
            self.render_children(qname, node, depth + 1, out, &mut own);
            for line in own {
                out.push_str(&line);
            }
            out.push_str(&format!("{pad}}}\n"));
            return;
        };
        let tname = type_name(elem);
        let Some((kw, is_def)) = elem.frontmatter.element_type.as_ref().and_then(kind_of) else {
            self.skip_subtree(qname, node, &pad, out);
            return;
        };
        *self.report.exported.entry(tname.clone()).or_insert(0) += 1;
        let fm = &elem.frontmatter;
        let native_req = matches!(fm.element_type, Some(ElementType::Requirement)) && fm.id.is_some();
        let is_package = kw == "package";

        // Label comment for id-identified elements whose free-prose name differs.
        if let Some(label) = fm.name.as_deref() {
            if label != name && !label.contains('\n') {
                out.push_str(&format!("{pad}// {name}: {label}\n"));
            }
        }

        // Header.
        let mut head = String::new();
        if fm.is_abstract == Some(true) && is_def {
            head.push_str("abstract ");
        }
        if fm.is_variation == Some(true) && is_def {
            head.push_str("variation ");
        }
        if fm.is_variant == Some(true) && !is_def {
            head.push_str("variant ");
        }
        head.push_str(kw);
        if is_def || native_req {
            if !is_package {
                head.push_str(" def");
            }
        }
        head.push(' ');
        head.push_str(&sysml_ident(name));
        let supers = ref_list(fm.supertype.as_ref());
        if !supers.is_empty() && (is_def || native_req) {
            let r: Vec<String> = supers.iter().map(|s| self.reference(s)).collect();
            head.push_str(&format!(" :> {}", r.join(", ")));
        }
        let typed = ref_list(fm.typed_by.as_ref());
        if !typed.is_empty() && !(is_def || native_req) && !is_package {
            let r: Vec<String> = typed.iter().map(|s| self.reference(s)).collect();
            head.push_str(&format!(" : {}", r.join(", ")));
        }
        if let Some(m) = fm.multiplicity.as_deref().map(str::trim).filter(|m| !m.is_empty() && *m != "1") {
            if !is_def && !is_package {
                head.push_str(&format!(" [{m}]"));
            }
        }
        if !is_def && !is_package && !native_req {
            // `REQ-TRS-SYSMLV2-049`: `:>` subsetting, `:>>` redefinition.
            let subs: Vec<String> = fm.subsets.iter().flatten().map(|s| self.reference(s)).collect();
            if !subs.is_empty() {
                head.push_str(&format!(" :> {}", subs.join(", ")));
            }
            let reds: Vec<String> = ref_list(fm.redefines.as_ref()).iter().map(|s| self.reference(s)).collect();
            if !reds.is_empty() {
                head.push_str(&format!(" :>> {}", reds.join(", ")));
            }
        }
        if matches!(fm.element_type, Some(ElementType::Attribute)) {
            if let Some(v) = fm.value.as_ref().and_then(render_value) {
                head.push_str(&format!(" = {v}"));
                // `REQ-TRS-SYSMLV2-055`: a numeric value carries its unit as a literal-with-unit.
                if let Some(u) = fm.unit.as_deref().map(str::trim).filter(|u| !u.is_empty() && v.parse::<f64>().is_ok()) {
                    head.push_str(&format!(" [{}]", sysml_unit(u)));
                }
            }
        }

        // Body members.
        let inner = "    ".repeat(depth + 1);
        let mut body = String::new();
        let doc = elem.doc.trim();
        if !doc.is_empty() {
            body.push_str(&render_doc(doc, &inner));
        }
        if matches!(fm.element_type, Some(ElementType::Part) | Some(ElementType::PartDef)) {
            self.push_syscribe_meta(elem, &inner, &mut body);
        }
        for f in fm.features.as_deref().unwrap_or(&[]) {
            if let Some(line) = self.render_feature(f) {
                body.push_str(&format!("{inner}{line}\n"));
            }
        }
        if matches!(fm.element_type, Some(ElementType::Part) | Some(ElementType::PartDef)) {
            for c in fm.connections.as_deref().unwrap_or(&[]) {
                if let Some(line) = self.render_connection(c) {
                    body.push_str(&format!("{inner}{line}\n"));
                }
            }
        }
        let sat = fm.satisfies.as_deref().unwrap_or(&[]);
        let in_part = matches!(fm.element_type, Some(ElementType::Part) | Some(ElementType::PartDef));
        for s in sat {
            if in_part {
                body.push_str(&format!("{inner}satisfy {};\n", self.reference(s)));
            } else if !is_package {
                // `REQ-TRS-SYSMLV2-051`: a real package-level statement.
                let pkg_pad = if is_package { String::new() } else { "    ".repeat(depth) };
                sats.push(format!("{pkg_pad}satisfy {} by {};\n", self.reference(s), qualified(qname)));
            }
        }
        // `REQ-TRS-SYSMLV2-051`: `verify` is accepted (and ingested) inside requirement bodies only.
        let is_req = matches!(fm.element_type, Some(ElementType::RequirementDef) | Some(ElementType::Requirement));
        for v in fm.verifies.as_deref().unwrap_or(&[]) {
            if is_req {
                body.push_str(&format!("{inner}verify {};\n", self.reference(v)));
            } else {
                body.push_str(&format!("{inner}// verifies: {v}\n"));
            }
        }
        self.push_behaviour_body(elem, &inner, &mut body);
        {
            // `REQ-TRS-SYSMLV2-056`..`-058`: action/state bodies, only as ingestion reads them back.
            let r = |s: &str| self.reference(s);
            match fm.element_type {
                Some(ElementType::ActionDef) => body.push_str(&super::export_behavior::action_body(fm, false, &inner, &r)),
                Some(ElementType::Action) => body.push_str(&super::export_behavior::action_body(fm, true, &inner, &r)),
                Some(ElementType::StateDef) | Some(ElementType::State) => {
                    body.push_str(&super::export_behavior::state_body(fm, &inner, &r))
                }
                _ => {}
            }
        }
        let mut child_buf = String::new();
        if is_package {
            let mut own = Vec::new();
            self.render_children(qname, node, depth + 1, &mut child_buf, &mut own);
            for line in own {
                child_buf.push_str(&line);
            }
        } else {
            self.render_children(qname, node, depth + 1, &mut child_buf, sats);
        }
        body.push_str(&child_buf);

        if body.is_empty() {
            out.push_str(&format!("{pad}{head};\n"));
        } else {
            out.push_str(&format!("{pad}{head} {{\n{body}{pad}}}\n"));
        }
    }

    fn render_children(
        &mut self,
        qname: &str,
        node: &Node<'_>,
        depth: usize,
        out: &mut String,
        sats: &mut Vec<String>,
    ) {
        for (name, child) in &node.children {
            let cq = format!("{qname}::{name}");
            self.render_node(name, &cq, child, depth, out, sats);
        }
    }

    /// `REQ-TRS-SYSMLV2-052`: `parameters:` and the opaque expression text of a
    /// constraint/calc, so ingestion's `expression:`/`body:` round-trips.
    fn push_behaviour_body(&self, e: &RawElement, inner: &str, body: &mut String) {
        let fm = &e.frontmatter;
        let (is_constraint, is_calc) = match fm.element_type {
            Some(ElementType::ConstraintDef) | Some(ElementType::Constraint) => (true, false),
            Some(ElementType::CalculationDef) | Some(ElementType::Calculation) => (false, true),
            _ => return,
        };
        for p in fm.parameters.as_deref().unwrap_or(&[]) {
            let Some(m) = p.as_mapping() else { continue };
            let get = |k: &str| m.get(serde_yaml::Value::String(k.to_string())).and_then(|v| v.as_str());
            let Some(pname) = get("name") else { continue };
            let dir = match get("direction") {
                Some("return") if is_calc => "return",
                Some("out") => "out",
                Some("inout") => "inout",
                _ => "in",
            };
            let mut line = format!("{dir} {}", sysml_ident(pname));
            if let Some(t) = get("typedBy") {
                line.push_str(&format!(" : {}", self.reference(t)));
            }
            body.push_str(&format!("{inner}{line};\n"));
        }
        let text = if is_constraint {
            fm.expression.as_deref()
        } else if is_calc && fm.body_language.as_deref().is_none_or(|l| l == "kerml") {
            fm.body.as_deref()
        } else {
            None
        };
        let Some(text) = text.map(str::trim).filter(|t| !t.is_empty()) else { return };
        let printable = !text.contains("expression>") && super::ingest::expression_round_trips(is_calc, text);
        if printable {
            for l in text.lines() {
                body.push_str(&format!("{inner}{}\n", l.trim()));
            }
        } else {
            for l in text.lines() {
                body.push_str(&format!("{inner}// expression (not valid SysML v2 text): {}\n", l.trim()));
            }
        }
    }

    fn skip_subtree(&mut self, qname: &str, node: &Node<'_>, pad: &str, out: &mut String) {
        if let Some(e) = node.elem {
            let t = type_name(e);
            out.push_str(&format!("{pad}// skipped: {qname} ({t})\n"));
            *self.report.skipped.entry(t.clone()).or_insert(0) += 1;
            self.report.skipped_elements.push((qname.to_string(), t));
        }
        for (name, child) in &node.children {
            let cq = format!("{qname}::{name}");
            self.skip_subtree(&cq, child, pad, out);
        }
    }

    fn push_syscribe_meta(&self, e: &RawElement, inner: &str, body: &mut String) {
        let fm = &e.frontmatter;
        if let Some(d) = fm.domain.as_deref() {
            body.push_str(&format!("{inner}@SyscribeDomain {{\n{inner}    value = '{}';\n{inner}}}\n", esc_single(d)));
        }
        if let Some(a) = fm.asil_level.as_deref() {
            body.push_str(&format!("{inner}@SyscribeIntegrity {{\n{inner}    asil = '{}';\n{inner}}}\n", esc_single(a)));
        }
        if let Some(s) = fm.short_name.as_deref() {
            body.push_str(&format!("{inner}@SyscribeShortName {{\n{inner}    value = '{}';\n{inner}}}\n", esc_single(s)));
        }
    }

    /// One inline `features:` entry as an `attribute`/`port` member.
    fn render_feature(&self, f: &serde_yaml::Value) -> Option<String> {
        let m = f.as_mapping()?;
        let get = |k: &str| m.get(serde_yaml::Value::String(k.to_string()));
        let name = get("name")?.as_str()?;
        let kind = match get("type").and_then(|v| v.as_str()) {
            Some("Port") => "port",
            Some("Item") => "item",
            Some("Part") => "part",
            _ => "attribute",
        };
        let mut s = format!("{kind} {}", sysml_ident(name));
        if let Some(t) = get("typedBy").or_else(|| get("type_")).and_then(|v| v.as_str()) {
            s.push_str(&format!(" : {}", self.reference(t)));
        }
        if let Some(mu) = get("multiplicity").and_then(|v| v.as_str()).filter(|m| *m != "1" && !m.is_empty()) {
            s.push_str(&format!(" [{mu}]"));
        }
        let unit = get("unit").and_then(|v| v.as_str()).map(str::trim).filter(|u| !u.is_empty());
        let mut unit_used = false;
        if kind == "attribute" {
            if let Some(v) = get("value").and_then(render_value) {
                s.push_str(&format!(" = {v}"));
                // `REQ-TRS-SYSMLV2-050`: a numeric value carries its unit as a literal-with-unit.
                if let Some(u) = unit.filter(|_| v.parse::<f64>().is_ok()) {
                    s.push_str(&format!(" [{}]", sysml_unit(u)));
                    unit_used = true;
                }
            }
        }
        s.push(';');
        if let Some(u) = unit.filter(|_| !unit_used) {
            s.push_str(&format!(" // unit: {u}"));
        }
        Some(s)
    }

    /// One `connections:` entry `{from, to, name?, typedBy?}`.
    fn render_connection(&self, c: &serde_yaml::Value) -> Option<String> {
        let m = c.as_mapping()?;
        let get = |k: &str| m.get(serde_yaml::Value::String(k.to_string())).and_then(|v| v.as_str());
        let from = get("from")?;
        let to = get("to")?;
        let end = |s: &str| s.split("::").map(sysml_ident).collect::<Vec<_>>().join(".");
        let mut s = String::from("connection");
        if let Some(n) = get("name") {
            s.push_str(&format!(" {}", sysml_ident(n)));
        }
        if let Some(t) = get("typedBy") {
            s.push_str(&format!(" : {}", self.reference(t)));
        }
        s.push_str(&format!(" connect {} to {};", end(from), end(to)));
        Some(s)
    }
}

/// A frontmatter reference field that is a string or a list of strings.
fn ref_list(v: Option<&serde_yaml::Value>) -> Vec<String> {
    match v {
        Some(serde_yaml::Value::String(s)) if !s.trim().is_empty() => vec![s.trim().to_string()],
        Some(serde_yaml::Value::Sequence(seq)) => seq
            .iter()
            .filter_map(|x| x.as_str().map(|s| s.trim().to_string()))
            .filter(|s| !s.is_empty())
            .collect(),
        _ => Vec::new(),
    }
}

/// A unit expression inside `[...]`: a bare/qualified name stays as is, anything
/// else is single-quoted as a restricted name.
fn sysml_unit(u: &str) -> String {
    if u.split("::").all(|seg| {
        let mut c = seg.chars();
        c.next().is_some_and(|f| f.is_ascii_alphabetic() || f == '_') && seg.chars().all(|x| x.is_ascii_alphanumeric() || x == '_')
    }) {
        u.to_string()
    } else {
        sysml_ident(u)
    }
}

fn esc_single(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// A scalar `value:` as a SysML literal (numbers/bools bare, text double-quoted).
fn render_value(v: &serde_yaml::Value) -> Option<String> {
    match v {
        serde_yaml::Value::Bool(b) => Some(b.to_string()),
        serde_yaml::Value::Number(n) => Some(n.to_string()),
        serde_yaml::Value::String(s) => {
            let t = s.trim();
            if t.parse::<f64>().is_ok() || t == "true" || t == "false" {
                Some(t.to_string())
            } else {
                Some(format!("\"{}\"", t.replace('\\', "\\\\").replace('"', "\\\"")))
            }
        }
        _ => None,
    }
}

/// `doc /* ... */`, with any `*/` in the text neutralized (`REQ-TRS-SYSMLV2-038`).
fn render_doc(doc: &str, pad: &str) -> String {
    let safe = doc.replace("*/", "* /");
    if !safe.contains('\n') {
        return format!("{pad}doc /* {safe} */\n");
    }
    let mut s = format!("{pad}doc /*\n");
    for line in safe.lines() {
        if line.trim().is_empty() {
            s.push('\n');
        } else {
            s.push_str(&format!("{pad}{line}\n"));
        }
    }
    s.push_str(&format!("{pad}*/\n"));
    s
}
