//! `syscribe build-config` — generate build-system artifacts from a `Configuration`.
//!
//! See `prompts/help/build-config.md` for the full man page.

use syscribe_model::{
    build_config,
    build_config::BuildVars,
    element::{ElementType, RawElement},
    validator::Severity,
};

// ── Format writers ────────────────────────────────────────────────────────────

/// Render a YAML scalar value as a CMake-style token.
/// Numbers: bare. Strings: quoted when they contain spaces. Booleans: ON/OFF.
fn cmake_val(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::Bool(b) => if *b { "ON".into() } else { "OFF".into() },
        serde_yaml::Value::Number(n) => n.to_string(),
        serde_yaml::Value::String(s) => {
            if s.contains(' ') {
                format!("\"{}\"", s)
            } else {
                s.clone()
            }
        }
        _ => format!("{:?}", v),
    }
}

/// Render a value for `#define` — numbers bare, strings quoted, booleans 1/0.
fn c_val(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::Bool(b) => if *b { "1".into() } else { "0".into() },
        serde_yaml::Value::Number(n) => n.to_string(),
        serde_yaml::Value::String(s) => format!("\"{}\"", s),
        _ => format!("{:?}", v),
    }
}

/// Render a value for a shell assignment (env / makefile).
/// Numbers/bools unquoted; strings with spaces quoted.
fn shell_val(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::Bool(b) => if *b { "1".into() } else { "0".into() },
        serde_yaml::Value::Number(n) => n.to_string(),
        serde_yaml::Value::String(s) => {
            if s.contains(' ') {
                format!("\"{}\"", s)
            } else {
                s.clone()
            }
        }
        _ => format!("{:?}", v),
    }
}

/// Render a value in Kconfig format.
/// true / 1 → y, false / 0 → n, other integers → bare, strings → quoted.
fn kconfig_val(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::Bool(b) => if *b { "y".into() } else { "n".into() },
        serde_yaml::Value::Number(n) => {
            // integer 1 → y, 0 → n
            if let Some(i) = n.as_i64() {
                if i == 1 { return "y".into(); }
                if i == 0 { return "n".into(); }
            }
            n.to_string()
        }
        serde_yaml::Value::String(s) => format!("\"{}\"", s),
        _ => format!("{:?}", v),
    }
}

/// Apply a non-empty prefix to a variable name.
fn prefixed(name: &str, prefix: &str) -> String {
    if prefix.is_empty() { name.to_string() } else { format!("{}{}", prefix, name) }
}

pub fn fmt_cmake(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by: syscribe build-config --config {} --format cmake\n",
        conf_id
    ));
    out.push_str(&format!("# Configuration: {} — \"{}\"\n", conf_id, conf_name));
    for (name, val) in vars {
        out.push_str(&format!("set({} {})\n", prefixed(name, prefix), cmake_val(val)));
    }
    out
}

pub fn fmt_c_header(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "/* Generated by: syscribe build-config --config {} --format c-header */\n",
        conf_id
    ));
    out.push_str(&format!("/* Configuration: {} — \"{}\" */\n", conf_id, conf_name));
    out.push_str("#ifndef SYSCRIBE_CONFIG_H\n");
    out.push_str("#define SYSCRIBE_CONFIG_H\n");
    for (name, val) in vars {
        out.push_str(&format!("#define {} {}\n", prefixed(name, prefix), c_val(val)));
    }
    out.push_str("#endif /* SYSCRIBE_CONFIG_H */\n");
    out
}

pub fn fmt_makefile(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by: syscribe build-config --config {} --format makefile\n",
        conf_id
    ));
    out.push_str(&format!("# Configuration: {} — \"{}\"\n", conf_id, conf_name));
    for (name, val) in vars {
        out.push_str(&format!("{} := {}\n", prefixed(name, prefix), shell_val(val)));
    }
    out
}

pub fn fmt_env(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by: syscribe build-config --config {} --format env\n",
        conf_id
    ));
    out.push_str(&format!("# Configuration: {} — \"{}\"\n", conf_id, conf_name));
    for (name, val) in vars {
        out.push_str(&format!("export {}={}\n", prefixed(name, prefix), shell_val(val)));
    }
    out
}

pub fn fmt_json(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let vars_json: serde_json::Map<String, serde_json::Value> = vars
        .iter()
        .map(|(k, v)| (prefixed(k, prefix), yaml_to_json(v)))
        .collect();
    let doc = serde_json::json!({
        "config": conf_id,
        "name": conf_name,
        "vars": vars_json,
    });
    serde_json::to_string_pretty(&doc).unwrap_or_default()
}

pub fn fmt_kconfig(vars: &BuildVars, conf_id: &str, conf_name: &str, prefix: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by: syscribe build-config --config {} --format kconfig\n",
        conf_id
    ));
    out.push_str(&format!("# Configuration: {} — \"{}\"\n", conf_id, conf_name));
    for (name, val) in vars {
        out.push_str(&format!(
            "CONFIG_{}={}\n",
            prefixed(name, prefix),
            kconfig_val(val)
        ));
    }
    out
}

// ── YAML → JSON value coercion ────────────────────────────────────────────────

fn yaml_to_json(v: &serde_yaml::Value) -> serde_json::Value {
    match v {
        serde_yaml::Value::Null => serde_json::Value::Null,
        serde_yaml::Value::Bool(b) => serde_json::Value::Bool(*b),
        serde_yaml::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                serde_json::Value::Number(i.into())
            } else if let Some(f) = n.as_f64() {
                serde_json::Number::from_f64(f)
                    .map(serde_json::Value::Number)
                    .unwrap_or(serde_json::Value::Null)
            } else {
                serde_json::Value::Null
            }
        }
        serde_yaml::Value::String(s) => serde_json::Value::String(s.clone()),
        serde_yaml::Value::Sequence(seq) => {
            serde_json::Value::Array(seq.iter().map(yaml_to_json).collect())
        }
        serde_yaml::Value::Mapping(m) => {
            let obj: serde_json::Map<String, serde_json::Value> = m
                .iter()
                .filter_map(|(k, v)| k.as_str().map(|ks| (ks.to_string(), yaml_to_json(v))))
                .collect();
            serde_json::Value::Object(obj)
        }
        _ => serde_json::Value::Null,
    }
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

/// Look up configuration metadata (id, display name) for a matched configuration.
fn conf_meta(elements: &[RawElement], conf_id: &str) -> (String, String) {
    let cfg = elements.iter().find(|e| {
        matches!(e.frontmatter.element_type, Some(ElementType::Configuration))
            && (e.frontmatter.id.as_deref() == Some(conf_id)
                || e.qualified_name == conf_id
                || e.qualified_name.ends_with(&format!("::{}", conf_id)))
    });
    let id = cfg
        .and_then(|e| e.frontmatter.id.as_deref())
        .unwrap_or(conf_id)
        .to_string();
    let name = cfg
        .and_then(|e| e.frontmatter.name.as_deref())
        .unwrap_or(conf_id)
        .to_string();
    (id, name)
}

fn dispatch_format(
    vars: &BuildVars,
    conf_id: &str,
    conf_name: &str,
    prefix: &str,
    format: &str,
) -> String {
    match format {
        "cmake" => fmt_cmake(vars, conf_id, conf_name, prefix),
        "c-header" => fmt_c_header(vars, conf_id, conf_name, prefix),
        "makefile" => fmt_makefile(vars, conf_id, conf_name, prefix),
        "env" => fmt_env(vars, conf_id, conf_name, prefix),
        "kconfig" => fmt_kconfig(vars, conf_id, conf_name, prefix),
        _ => fmt_json(vars, conf_id, conf_name, prefix),
    }
}

// ── Public CLI commands ───────────────────────────────────────────────────────

/// `syscribe build-config --config <id> --format <fmt> [--prefix <p>] [--no-validate]`
pub fn cmd_build_config(
    elements: &[RawElement],
    conf: &str,
    format: &str,
    prefix: &str,
    no_validate: bool,
) {
    // Step 1: optional SAT validation gate.
    if !no_validate {
        use syscribe_model::feature_model;
        if feature_model::has_feature_model(elements) {
            let findings = feature_model::check_feature_model(elements);
            let errors: Vec<_> = findings
                .iter()
                .filter(|f| f.severity == Severity::Error)
                .collect();
            if !errors.is_empty() {
                for e in &errors {
                    eprintln!("{}", e);
                }
                eprintln!(
                    "Feature model validation failed. Fix the errors above or re-run with --no-validate."
                );
                std::process::exit(1);
            }
        }
    }

    // Step 2: resolve build variables.
    let result = match build_config::resolve(elements, conf) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("error: {}", e);
            std::process::exit(1);
        }
    };

    // Step 3: abort on E050 findings. W050 is opt-in and surfaced via `validate
    // --deny W050` only — do not print it here.
    let mut has_e050 = false;
    for f in &result.findings {
        if f.code == "E050" {
            eprintln!("[ERROR] {} {}: {}", f.code, f.file, f.message);
            has_e050 = true;
        }
    }
    if has_e050 {
        std::process::exit(1);
    }

    // Step 4: apply prefix to all var names and emit output.
    let (conf_id_resolved, conf_name) = conf_meta(elements, conf);
    let output = dispatch_format(&result.vars, &conf_id_resolved, &conf_name, prefix, format);
    print!("{}", output);
}

/// `syscribe build-config --all-configs [--format json] [--prefix <p>] [--no-validate]`
///
/// Emits a JSON array of `{config, name, vars, error?}` — one entry per
/// `Configuration` in the model. Errors (E050, resolve failure) are captured
/// into the `error` field rather than aborting.
pub fn cmd_build_config_all(
    elements: &[RawElement],
    format: &str,
    prefix: &str,
    no_validate: bool,
) {
    // Optional SAT validation gate (same as single-config path).
    if !no_validate {
        use syscribe_model::feature_model;
        if feature_model::has_feature_model(elements) {
            let findings = feature_model::check_feature_model(elements);
            let errors: Vec<_> = findings
                .iter()
                .filter(|f| f.severity == Severity::Error)
                .collect();
            if !errors.is_empty() {
                for e in &errors {
                    eprintln!("{}", e);
                }
                eprintln!(
                    "Feature model validation failed. Fix the errors above or re-run with --no-validate."
                );
                std::process::exit(1);
            }
        }
    }

    let configs: Vec<&RawElement> = elements
        .iter()
        .filter(|e| matches!(e.frontmatter.element_type, Some(ElementType::Configuration)))
        .collect();

    if configs.is_empty() {
        println!("[]");
        return;
    }

    // For --all-configs we always use JSON regardless of --format (the spec says
    // "always json for --all-configs"), but we still accept --format json as the
    // explicit default.
    let _ = format; // format is always json for all-configs

    let mut entries: Vec<serde_json::Value> = Vec::new();

    for cfg in configs {
        let id = cfg
            .frontmatter
            .id
            .as_deref()
            .unwrap_or(&cfg.qualified_name)
            .to_string();
        let name = cfg
            .frontmatter
            .name
            .as_deref()
            .unwrap_or(&id)
            .to_string();

        match build_config::resolve(elements, &id) {
            Ok(result) => {
                // Collect E050 messages as error text. W050 is opt-in and not
                // printed here — use `validate --deny W050` to surface it.
                let mut error_msgs: Vec<String> = Vec::new();
                for f in &result.findings {
                    if f.code == "E050" {
                        error_msgs.push(format!("{}: {}", f.code, f.message));
                    }
                }

                let vars_json: serde_json::Map<String, serde_json::Value> = result
                    .vars
                    .iter()
                    .map(|(k, v)| (prefixed(k, prefix), yaml_to_json(v)))
                    .collect();

                let mut entry = serde_json::json!({
                    "config": id,
                    "name": name,
                    "vars": vars_json,
                });

                if !error_msgs.is_empty() {
                    entry["error"] = serde_json::json!(error_msgs.join("; "));
                }

                entries.push(entry);
            }
            Err(e) => {
                entries.push(serde_json::json!({
                    "config": id,
                    "name": name,
                    "vars": {},
                    "error": e,
                }));
            }
        }
    }

    let output = serde_json::to_string_pretty(&entries).unwrap_or_default();
    println!("{}", output);
}

