@startuml PowerSystemIBD
!include /home/sjames/playground/syscribe/.plantuml/sysml.iuml

rectangle "PowerSystem" as s_boundary [[https://github.com/sjames/syscribe/blob/main/model/UAV/Power/PowerSystem.md]] {
  rectangle "battery" as s_battery [[https://github.com/sjames/syscribe/blob/main/model/UAV/Power/PowerSystem/battery.md]] {
  }
  rectangle "pdu" as s_pdu [[https://github.com/sjames/syscribe/blob/main/model/UAV/Power/PowerSystem/pdu.md]] {
  }
}

s_battery --> s_pdu : flow
s_pdu ..> s_boundary : binding

@enduml
