@startuml UAVSystemBDD
!include /home/sjames/playground/syscribe/.plantuml/sysml.iuml
hide empty members

class "UAVSystem" as s_uavsystem <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/UAVSystem.md]]
class "Airframe" as s_airframe <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/Airframe.md]]
class "PropulsionSystem" as s_propulsion <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/Propulsion/PropulsionSystem.md]]
class "AvionicsBay" as s_avionics <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/Avionics/AvionicsBay.md]]
class "PowerSystem" as s_power <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/Power/PowerSystem.md]]
class "PayloadBay" as s_payload <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/UAV/Payload/PayloadBay.md]]
class "GroundControlStation" as s_gcs <<part def>> [[https://github.com/sjames/syscribe/blob/main/model/GroundStation/GroundControlStation.md]]

s_uavsystem *-- s_airframe : airframe
s_uavsystem *-- s_propulsion : propulsion
s_uavsystem *-- s_avionics : avionics
s_uavsystem *-- s_power : power
s_uavsystem *-- s_payload : payload
s_uavsystem ..> s_gcs : gcs

@enduml
