@startuml SensorHierarchy
skinparam class {
  BackgroundColor #f5f5fa
  BorderColor #3a3a4a
}
hide empty members

class "Sensor" as sensor_block <<part>> 
class "Crankshaft Position Sensor" as cps_block <<part>> 
class "Throttle Position Sensor" as tps_block <<part>> 
class "Lambda Sensor" as lambda_block <<part>> 

cps_block --|> sensor_block : cps-inherit
tps_block --|> sensor_block : tps-inherit
lambda_block --|> sensor_block : lambda-inherit

@enduml
