//! Generated name inventories of the SysML v2 Quantities-and-Units library (GH #210).
//!
//! Package-level member names (including short names and aliases) of `ISQ*`, `SI`,
//! `SIPrefixes` and `USCustomaryUnits`, extracted from the OMG SysML v2 standard library
//! (`Domain Libraries/Quantities and Units/`). Used so a bare name under a library
//! wildcard import (`import ISQ::*;`) is checked against a complete table.

pub const ISQ_NAMES: &[&str] = &[
    "AbsoluteActivityValue", "AbsorbedDoseRateUnit", "AbsorbedDoseRateValue",
    "AbsorbedDoseUnit", "AbsorbedDoseValue", "AbsorptanceValue", "AbsorptionNumberValue",
    "AccelerationUnit", "AccelerationValue", "AcceptorDensityUnit", "AcceptorDensityValue",
    "AcousticImpedanceUnit", "AcousticImpedanceValue", "ActionQuantityUnit",
    "ActionQuantityValue", "ActivityCoefficientValue", "ActivityConcentrationUnit",
    "ActivityConcentrationValue", "ActivityDensityUnit", "ActivityDensityValue",
    "ActivityFactorValue", "ActivityOfSoluteValue", "ActivityOfSolventValue", "AdmittanceUnit",
    "AdmittanceValue", "AffinityOfAChemicalReactionUnit", "AffinityOfAChemicalReactionValue",
    "AmountOfSubstanceConcentrationUnit", "AmountOfSubstanceConcentrationValue",
    "AmountOfSubstanceFractionMoleFractionValue", "AmountOfSubstanceUnit",
    "AmountOfSubstanceValue", "AngularAccelerationUnit", "AngularAccelerationValue",
    "AngularFrequencyUnit", "AngularFrequencyValue", "AngularImpulseUnit",
    "AngularImpulseValue", "AngularMeasureUnit", "AngularMeasureValue", "AngularMomentumUnit",
    "AngularMomentumValue", "AngularReciprocalLatticeVectorMagnitudeUnit",
    "AngularReciprocalLatticeVectorMagnitudeValue", "AngularRepetencyUnit",
    "AngularRepetencyValue", "AngularVelocityUnit", "AngularVelocityValue",
    "AngularWavenumberUnit", "AngularWavenumberValue", "ArchimedesNumberValue", "AreaUnit",
    "AreaValue", "AreicElectricChargeUnit", "AreicElectricChargeValue", "ArrheniusNumberValue",
    "AtomicAttenuationCoefficientUnit", "AtomicAttenuationCoefficientValue",
    "AtomicScatteringFactorValue", "AttenuationUnit", "AttenuationValue", "AtwoodNumberValue",
    "AverageConditionalInformationContentUnit", "AverageConditionalInformationContentValue",
    "AverageEnergyLossPerElementaryChargeProducedUnit",
    "AverageEnergyLossPerElementaryChargeProducedValue", "AverageInformationRateUnit",
    "AverageInformationRateValue", "AverageLogarithmicEnergyDecrementValue",
    "AverageTransinformationRateUnit", "AverageTransinformationRateValue",
    "BagnoldNumberForSolidParticlesValue", "BagnoldNumberValue", "BatchelorNumberValue",
    "BejanNumberForEntropyValue", "BejanNumberForHeatTransferValue",
    "BejanNumberForMassTransferValue", "BejanNumberValue", "BinaryDigitRateUnit",
    "BinaryDigitRateValue", "BindingFractionValue", "BinghamNumberValue",
    "BiotNumberForMassTransferValue", "BiotNumberValue", "BitRateUnit", "BitRateValue",
    "BlakeNumberValue", "BodensteinNumberValue", "BoltzmannNumberValue", "BondNumberValue",
    "BrinkmanNumberValue", "BulkModulusUnit", "BulkModulusValue", "CallIntensityUnit",
    "CallIntensityValue", "CallingRateUnit", "CallingRateValue",
    "CanonicalPartitionFunctionValue", "CapacitanceUnit", "CapacitanceValue",
    "CapillaryNumberValue", "CarnotNumberValue",
    "Cartesian3dMomentOfInertiaMeasurementReference", "Cartesian3dMomentOfInertiaTensor",
    "Cartesian3dStrainMeasurementReference", "Cartesian3dStrainTensor",
    "Cartesian3dStressMeasurementReference", "Cartesian3dStressTensor",
    "CartesianAcceleration3dCoordinateFrame", "CartesianAcceleration3dVector",
    "CartesianAngularAcceleration3dCoordinateFrame", "CartesianAngularAcceleration3dVector",
    "CartesianAngularImpulse3dCoordinateFrame", "CartesianAngularImpulse3dVector",
    "CartesianAngularMomentum3dCoordinateFrame", "CartesianAngularMomentum3dVector",
    "CartesianAngularReciprocalLattice3dCoordinateFrame",
    "CartesianAngularReciprocalLattice3dVector", "CartesianAngularVelocity3dCoordinateFrame",
    "CartesianAngularVelocity3dVector", "CartesianAreicElectricCurrent3dCoordinateFrame",
    "CartesianBurgers3dVector", "CartesianDisplacement3dVector",
    "CartesianDisplacementCurrentDensity3dCoordinateFrame",
    "CartesianDisplacementCurrentDensity3dVector", "CartesianDragForce3dVector",
    "CartesianElectricCurrentDensity3dCoordinateFrame",
    "CartesianElectricCurrentDensity3dVector", "CartesianElectricDipoleMoment3dCoordinateFrame",
    "CartesianElectricDipoleMoment3dVector", "CartesianElectricDisplacement3dCoordinateFrame",
    "CartesianElectricFieldStrength3dCoordinateFrame", "CartesianElectricFieldStrength3dVector",
    "CartesianElectricFluxDensity3dCoordinateFrame", "CartesianElectricFluxDensity3dVector",
    "CartesianElectricPolarization3dCoordinateFrame", "CartesianElectricPolarization3dVector",
    "CartesianEquilibriumPosition3dVector", "CartesianForce3dCoordinateFrame",
    "CartesianForce3dVector", "CartesianFundamentalLattice3dVector",
    "CartesianFundamentalReciprocalLattice3dCoordinateFrame",
    "CartesianFundamentalReciprocalLattice3dVector", "CartesianImpulse3dCoordinateFrame",
    "CartesianImpulse3dVector", "CartesianKineticFrictionForce3dVector",
    "CartesianLattice3dVector", "CartesianLinearElectricCurrentDensity3dCoordinateFrame",
    "CartesianLinearElectricCurrentDensity3dVector",
    "CartesianLineicElectricCurrent3dCoordinateFrame",
    "CartesianMagneticAreaMoment3dCoordinateFrame",
    "CartesianMagneticDipoleMoment3dCoordinateFrame", "CartesianMagneticDipoleMoment3dVector",
    "CartesianMagneticFieldStrength3dCoordinateFrame", "CartesianMagneticFieldStrength3dVector",
    "CartesianMagneticFluxDensity3dCoordinateFrame", "CartesianMagneticFluxDensity3dVector",
    "CartesianMagneticMoment3dCoordinateFrame", "CartesianMagneticMoment3dVector",
    "CartesianMagneticPolarization3dCoordinateFrame", "CartesianMagneticPolarization3dVector",
    "CartesianMagneticVectorPotential3dCoordinateFrame",
    "CartesianMagneticVectorPotential3dVector", "CartesianMagnetization3dCoordinateFrame",
    "CartesianMagnetization3dVector", "CartesianMagnetizingField3dCoordinateFrame",
    "CartesianMassFlow3dCoordinateFrame", "CartesianMassFlow3dVector",
    "CartesianMomentOfForce3dCoordinateFrame", "CartesianMomentOfForce3dVector",
    "CartesianMomentum3dCoordinateFrame", "CartesianMomentum3dVector",
    "CartesianParticleCurrentDensity3dCoordinateFrame",
    "CartesianParticleCurrentDensity3dVector", "CartesianParticlePosition3dVector",
    "CartesianPosition3dVector", "CartesianPoynting3dCoordinateFrame",
    "CartesianPoynting3dVector", "CartesianRollingResistance3dVector",
    "CartesianSoundIntensity3dCoordinateFrame", "CartesianSoundIntensity3dVector",
    "CartesianSoundParticleAcceleration3dVector", "CartesianSoundParticleDisplacement3dVector",
    "CartesianSoundParticleVelocity3dVector", "CartesianSpatial3dCoordinateFrame",
    "CartesianSpin3dCoordinateFrame", "CartesianSpin3dVector",
    "CartesianStaticFrictionForce3dVector", "CartesianTotalAngularMomentum3dCoordinateFrame",
    "CartesianTotalAngularMomentum3dVector", "CartesianTotalCurrentDensity3dCoordinateFrame",
    "CartesianTotalCurrentDensity3dVector", "CartesianVelocity3dCoordinateFrame",
    "CartesianVelocity3dVector", "CartesianWave3dVector",
    "CartesianWaveVector3dCoordinateFrame", "CartesianWeight3dVector", "CauchyNumberValue",
    "CavitationNumberValue", "CelsiusTemperatureUnit", "CelsiusTemperatureValue",
    "ChandrasekharNumberValue", "ChannelCapacityPerCharacterUnit",
    "ChannelCapacityPerCharacterValue", "ChannelCapacityUnit", "ChannelCapacityValue",
    "ChannelTimeCapacityUnit", "ChannelTimeCapacityValue", "CharacterMeanEntropyUnit",
    "CharacterMeanEntropyValue", "CharacterMeanTransinformationContentUnit",
    "CharacterMeanTransinformationContentValue",
    "CharacteristicImpedanceOfAMediumForLongitudinalWavesUnit",
    "CharacteristicImpedanceOfAMediumForLongitudinalWavesValue", "ChargeNumberValue",
    "ChemicalPotentialUnit", "ChemicalPotentialValue",
    "ChromaticityCoordinatesInTheCie1931StandardColorimetricSystemValue",
    "ChromaticityCoordinatesInTheCie1964StandardColorimetricSystemValue",
    "CieColourMatchingFunctionsForTheCie1931StandardColorimetricObserverValue",
    "CieColourMatchingFunctionsForTheCie1964StandardColorimetricObserverValue",
    "ClausiusNumberValue", "CoefficientOfHeatTransferUnit", "CoefficientOfHeatTransferValue",
    "CoefficientOfThermalInsulanceUnit", "CoefficientOfThermalInsulanceValue", "CoercivityUnit",
    "CoercivityValue", "CompletedCallIntensityUnit", "CompletedCallIntensityValue",
    "ComplexAdmittanceUnit", "ComplexAdmittanceValue", "ComplexImpedanceUnit",
    "ComplexImpedanceValue", "CompressibilityNumberValue", "CompressibilityUnit",
    "CompressibilityValue", "ConditionalEntropyUnit", "ConditionalEntropyValue",
    "ConditionalInformationContentUnit", "ConditionalInformationContentValue",
    "ConductanceUnit", "ConductanceValue", "ConductivityUnit", "ConductivityValue",
    "CouplingFactorValue", "CowlingNumberValue", "CubicExpansionCoefficientUnit",
    "CubicExpansionCoefficientValue", "CurvatureUnit", "CurvatureValue",
    "CylindricalDisplacement3dVector", "CylindricalPosition3dVector",
    "CylindricalSpatial3dCoordinateFrame", "DampingCoefficientUnit", "DampingCoefficientValue",
    "DarcyFrictionFactorValue", "DeanNumberValue", "DeborahNumberValue",
    "DebyeWallerFactorValue", "DecayConstantUnit", "DecayConstantValue", "DecisionContentValue",
    "DegeneracyValue", "DegreeOfDissociationValue", "DensityOfHeatFlowRateUnit",
    "DensityOfHeatFlowRateValue", "DensityOfVibrationalStatesUnit",
    "DensityOfVibrationalStatesValue", "DensityUnit", "DensityValue",
    "DiffusionCoefficientForParticleNumberDensityUnit",
    "DiffusionCoefficientForParticleNumberDensityValue", "DiffusionCoefficientUnit",
    "DiffusionCoefficientValue", "DirectionAndEnergyDistributionOfCrossSectionUnit",
    "DirectionAndEnergyDistributionOfCrossSectionValue",
    "DirectionDistributionOfCrossSectionUnit", "DirectionDistributionOfCrossSectionValue",
    "DisintegrationConstantUnit", "DisintegrationConstantValue", "Displacement3dVector",
    "DisplacementCurrentDensityUnit", "DisplacementCurrentDensityValue", "DonorDensityUnit",
    "DonorDensityValue", "DoseEquivalentUnit", "DoseEquivalentValue", "DragCoefficientValue",
    "DurationUnit", "DurationValue", "DynamicCapillaryNumberValue", "DynamicViscosityUnit",
    "DynamicViscosityValue", "EckertNumberValue", "EkmanNumberValue", "ElasticityNumberValue",
    "ElectricChargeDensityUnit", "ElectricChargeDensityValue", "ElectricChargeUnit",
    "ElectricChargeValue", "ElectricConstantUnit", "ElectricConstantValue",
    "ElectricCurrentDensityUnit", "ElectricCurrentDensityValue", "ElectricCurrentUnit",
    "ElectricCurrentValue", "ElectricDipoleMomentUnit", "ElectricDipoleMomentValue",
    "ElectricFieldParameterValue", "ElectricFieldStrengthUnit", "ElectricFieldStrengthValue",
    "ElectricFluxDensityUnit", "ElectricFluxDensityValue", "ElectricFluxUnit",
    "ElectricFluxValue", "ElectricPolarizationUnit", "ElectricPolarizationValue",
    "ElectricPotentialDifferenceUnit", "ElectricPotentialDifferenceValue",
    "ElectricPotentialUnit", "ElectricPotentialValue", "ElectricSusceptibilityValue",
    "ElectrolyticConductivityUnit", "ElectrolyticConductivityValue",
    "ElectromagneticEnergyDensityUnit", "ElectromagneticEnergyDensityValue",
    "ElectronDensityUnit", "ElectronDensityValue", "EmissivityAtASpecifiedWavelengthValue",
    "EmissivityValue", "EnergyDensityOfStatesUnit", "EnergyDensityOfStatesValue",
    "EnergyDistributionOfCrossSectionUnit", "EnergyDistributionOfCrossSectionValue",
    "EnergyFluenceRateUnit", "EnergyFluenceRateValue", "EnergyFluenceUnit",
    "EnergyFluenceValue", "EnergyUnit", "EnergyValue", "EntropyForInformationScienceUnit",
    "EntropyForInformationScienceValue", "EntropyUnit", "EntropyValue",
    "EquilibriumConstantOnConcentrationBasisUnit",
    "EquilibriumConstantOnConcentrationBasisValue", "EquilibriumConstantOnPressureBasisUnit",
    "EquilibriumConstantOnPressureBasisValue", "EquivalentBinaryDigitRateUnit",
    "EquivalentBinaryDigitRateValue", "EquivalentBinaryStorageCapacityUnit",
    "EquivalentBinaryStorageCapacityValue", "EquivalentBitRateUnit", "EquivalentBitRateValue",
    "EquivocationUnit", "EquivocationValue", "ErrorProbabilityValue", "EulerNumberValue",
    "ExpansionNumberValue", "ExposureRateUnit", "ExposureRateValue", "ExposureUnit",
    "ExposureValue", "ExtinctionUnit", "ExtinctionValue", "FanningNumberValue",
    "FastFissionFactorUnit", "FastFissionFactorValue", "ForceUnit", "ForceValue",
    "FourierNumberForMassTransferValue", "FourierNumberValue", "FrequencyUnit",
    "FrequencyValue", "FroudeNumberForHeatTransferValue", "FroudeNumberValue", "FugacityUnit",
    "FugacityValue", "FundamentalReciprocalLatticeVectorMagnitudeUnit",
    "FundamentalReciprocalLatticeVectorMagnitudeValue",
    "GFactorOfNucleusOrNuclearParticleValue", "GalileiNumberValue", "GoertlerNumberValue",
    "GraetzNumberForMassTransferValue", "GraetzNumberValue",
    "GrandCanonicalPartitionFunctionValue", "GrashofMagneticNumberValue",
    "GrashofNumberForMassTransferValue", "GrashofNumberValue",
    "GyromagneticCoefficientOfTheElectronUnit", "GyromagneticCoefficientOfTheElectronValue",
    "GyromagneticCoefficientUnit", "GyromagneticCoefficientValue",
    "GyromagneticRatioOfTheElectronUnit", "GyromagneticRatioOfTheElectronValue",
    "GyromagneticRatioUnit", "GyromagneticRatioValue", "HagenNumberValue",
    "HallCoefficientUnit", "HallCoefficientValue", "HallNumberValue", "HartmannNumberValue",
    "HartreeEnergyUnit", "HartreeEnergyValue", "HeatCapacityUnit", "HeatCapacityValue",
    "HeatFlowRateUnit", "HeatFlowRateValue", "HeatTransferNumberValue", "HoleDensityUnit",
    "HoleDensityValue", "HookeNumberValue", "IlluminanceUnit", "IlluminanceValue",
    "ImpedanceUnit", "ImpedanceValue", "ImpulseUnit", "ImpulseValue", "InductanceUnit",
    "InductanceValue", "InfiniteMultiplicationFactorUnit", "InfiniteMultiplicationFactorValue",
    "InformationContentUnit", "InformationContentValue", "InternalConversionFactorValue",
    "IntrinsicCarrierDensityUnit", "IntrinsicCarrierDensityValue", "IonDensityUnit",
    "IonDensityValue", "IonNumberDensityUnit", "IonNumberDensityValue", "IonicStrengthUnit",
    "IonicStrengthValue", "IrradianceUnit", "IrradianceValue", "IrrelevanceUnit",
    "IrrelevanceValue", "IsentropicCompressibilityUnit", "IsentropicCompressibilityValue",
    "IsentropicExponentValue", "IsothermalCompressibilityUnit",
    "IsothermalCompressibilityValue", "JFactorValue", "JointInformationContentUnit",
    "JointInformationContentValue", "JouleMagneticNumberValue", "JouleThomsonCoefficientUnit",
    "JouleThomsonCoefficientValue", "KermaRateUnit", "KermaRateValue", "KermaUnit",
    "KermaValue", "KinematicViscosityUnit", "KinematicViscosityValue",
    "KineticFrictionFactorValue", "KnudsenNumberValue", "LagrangeNumberValue",
    "LandauGinzburgNumberValue", "LandeFactorValue", "LaplaceNumberValue",
    "LarmorFrequencyUnit", "LarmorFrequencyValue", "LavalNumberValue", "LeakageFactorValue",
    "LengthUnit", "LengthValue", "LethargyValue", "LewisNumberValue", "LiftCoefficientValue",
    "LightExposureUnit", "LightExposureValue", "LightSpeedUnit", "LightSpeedValue",
    "LineDigitRateUnit", "LineDigitRateValue", "LinearAbsorptionCoefficientUnit",
    "LinearAbsorptionCoefficientValue", "LinearAttenuationCoefficientForIonizingRadiationUnit",
    "LinearAttenuationCoefficientForIonizingRadiationValue", "LinearAttenuationCoefficientUnit",
    "LinearAttenuationCoefficientValue", "LinearDensityOfElectricChargeUnit",
    "LinearDensityOfElectricChargeValue", "LinearDensityUnit", "LinearDensityValue",
    "LinearElectricCurrentDensityUnit", "LinearElectricCurrentDensityValue",
    "LinearEnergyTransferUnit", "LinearEnergyTransferValue", "LinearExpansionCoefficientUnit",
    "LinearExpansionCoefficientValue", "LinearExtinctionCoefficientUnit",
    "LinearExtinctionCoefficientValue", "LinearIonizationUnit", "LinearIonizationValue",
    "LinearMassDensityUnit", "LinearMassDensityValue", "LinearStoppingPowerUnit",
    "LinearStoppingPowerValue", "LineicElectricChargeUnit", "LineicElectricChargeValue",
    "LinkedFluxUnit", "LinkedFluxValue", "LockhartMartinelliParameterValue",
    "LogarithmicDecrementValue", "LogarithmicFrequencyRangeUnit",
    "LogarithmicFrequencyRangeValue", "LongRangeOrderParameterValue", "LorentzNumberValue",
    "LorenzCoefficientUnit", "LorenzCoefficientValue", "LossFactorValue",
    "LossProbabilityValue", "LuminanceFactorValue", "LuminanceUnit", "LuminanceValue",
    "LuminousAbsorptanceValue", "LuminousEfficacyOfASourceUnit",
    "LuminousEfficacyOfASourceValue", "LuminousEfficacyOfRadiationUnit",
    "LuminousEfficacyOfRadiationValue", "LuminousEfficiencyValue", "LuminousEnergyUnit",
    "LuminousEnergyValue", "LuminousExitanceUnit", "LuminousExitanceValue",
    "LuminousExposureUnit", "LuminousExposureValue", "LuminousFluxUnit", "LuminousFluxValue",
    "LuminousIntensityUnit", "LuminousIntensityValue", "LuminousReflectanceValue",
    "LuminousTransmittanceValue", "LundquistNumberValue", "MachNumberValue",
    "MacroscopicCrossSectionUnit", "MacroscopicCrossSectionValue",
    "MacroscopicTotalCrossSectionUnit", "MacroscopicTotalCrossSectionValue",
    "MagneticConstantUnit", "MagneticConstantValue", "MagneticDipoleMomentUnit",
    "MagneticDipoleMomentValue", "MagneticFieldStrengthUnit", "MagneticFieldStrengthValue",
    "MagneticFluxDensityUnit", "MagneticFluxDensityValue", "MagneticFluxUnit",
    "MagneticFluxValue", "MagneticMomentUnit", "MagneticMomentValue", "MagneticNumberValue",
    "MagneticPolarizationUnit", "MagneticPolarizationValue", "MagneticPressureNumberValue",
    "MagneticSusceptibilityValue", "MagneticVectorPotentialUnit",
    "MagneticVectorPotentialValue", "MagnetizationUnit", "MagnetizationValue",
    "MagnetogyricRatioOfTheElectronUnit", "MagnetogyricRatioOfTheElectronValue",
    "MagnetogyricRatioUnit", "MagnetogyricRatioValue", "MagnetomotiveForceUnit",
    "MagnetomotiveForceValue", "MarangoniNumberValue", "MassAbsorptionCoefficientUnit",
    "MassAbsorptionCoefficientValue", "MassAttenuationCoefficientForIonizingRadiationUnit",
    "MassAttenuationCoefficientForIonizingRadiationValue", "MassAttenuationCoefficientUnit",
    "MassAttenuationCoefficientValue", "MassChangeRateUnit", "MassChangeRateValue",
    "MassConcentrationOfWaterUnit", "MassConcentrationOfWaterValue",
    "MassConcentrationOfWaterVapourAbsoluteHumidityUnit",
    "MassConcentrationOfWaterVapourAbsoluteHumidityValue", "MassConcentrationUnit",
    "MassConcentrationValue", "MassDensityUnit", "MassDensityValue",
    "MassEnergyTransferCoefficientUnit", "MassEnergyTransferCoefficientValue",
    "MassFlowRateUnit", "MassFlowRateValue", "MassFlowUnit", "MassFlowValue",
    "MassFractionOfDryMatterValue", "MassFractionOfWaterValue", "MassFractionValue",
    "MassRatioOfWaterToDryMatterValue", "MassRatioOfWaterVapourToDryGasValue",
    "MassStoppingPowerUnit", "MassStoppingPowerValue", "MassTransferFactorValue", "MassUnit",
    "MassValue", "MassicActivityUnit", "MassicActivityValue", "MassieuFunctionUnit",
    "MassieuFunctionValue", "MaximumEntropyUnit", "MaximumEntropyValue",
    "MaximumLuminousEfficacyUnit", "MaximumLuminousEfficacyValue",
    "MaximumThermalEfficiencyValue", "MeanConditionalInformationContentUnit",
    "MeanConditionalInformationContentValue", "MeanMassRangeUnit", "MeanMassRangeValue",
    "MeanQueueLengthValue", "MeanTransinformationContentUnit",
    "MeanTransinformationContentValue", "MechanicalEfficiencyValue", "MobilityRatioValue",
    "MobilityUnit", "MobilityValue", "ModulationRateUnit", "ModulationRateValue",
    "ModulusOfAdmittanceUnit", "ModulusOfAdmittanceValue", "ModulusOfCompressionUnit",
    "ModulusOfCompressionValue", "ModulusOfElasticityUnit", "ModulusOfElasticityValue",
    "ModulusOfImpedanceUnit", "ModulusOfImpedanceValue", "ModulusOfRigidityUnit",
    "ModulusOfRigidityValue", "MolalityUnit", "MolalityValue", "MolarAbsorptionCoefficientUnit",
    "MolarAbsorptionCoefficientValue", "MolarAttenuationCoefficientUnit",
    "MolarAttenuationCoefficientValue", "MolarConductivityUnit", "MolarConductivityValue",
    "MolarEnthalpyUnit", "MolarEnthalpyValue", "MolarEntropyUnit", "MolarEntropyValue",
    "MolarGasConstantUnit", "MolarGasConstantValue", "MolarGibbsEnergyUnit",
    "MolarGibbsEnergyValue", "MolarHeatCapacityUnit", "MolarHeatCapacityValue",
    "MolarHelmholtzEnergyUnit", "MolarHelmholtzEnergyValue", "MolarInternalEnergyUnit",
    "MolarInternalEnergyValue", "MolarMassUnit", "MolarMassValue",
    "MolarOpticalRotatoryPowerUnit", "MolarOpticalRotatoryPowerValue", "MolarVolumeUnit",
    "MolarVolumeValue", "MolecularPartitionFunctionValue", "MomentOfForceUnit",
    "MomentOfForceValue", "MomentOfInertiaUnit", "MomentOfInertiaValue", "MomentumUnit",
    "MomentumValue", "MortonNumberValue", "MultiplicationFactorUnit",
    "MultiplicationFactorValue", "NapierianAbsorbanceValue", "NazeNumberValue",
    "NonLeakageProbabilityUnit", "NonLeakageProbabilityValue", "NormalStressUnit",
    "NormalStressValue", "NuclearActivityUnit", "NuclearActivityValue",
    "NuclearQuadrupoleMomentUnit", "NuclearQuadrupoleMomentValue", "NumberOfMolesUnit",
    "NumberOfMolesValue", "NusseltElectricNumberValue", "NusseltNumberForMassTransferValue",
    "NusseltNumberValue", "OhnesorgeNumberValue", "OsmoticFactorOfSolventValue",
    "OsmoticPressureUnit", "OsmoticPressureValue", "PackingFractionValue",
    "PartialPressureUnit", "PartialPressureValue", "ParticleConcentrationUnit",
    "ParticleConcentrationValue", "ParticleCurrentDensityUnit", "ParticleCurrentDensityValue",
    "ParticleEmissionRateUnit", "ParticleEmissionRateValue", "ParticleFluenceRateUnit",
    "ParticleFluenceRateValue", "ParticleFluenceUnit", "ParticleFluenceValue",
    "ParticleNumberDensityUnit", "ParticleNumberDensityValue", "ParticleSourceDensityUnit",
    "ParticleSourceDensityValue", "PermeabilityOfVacuumUnit", "PermeabilityOfVacuumValue",
    "PermeabilityUnit", "PermeabilityValue", "PermeanceUnit", "PermeanceValue",
    "PermittivityOfVacuumUnit", "PermittivityOfVacuumValue", "PermittivityUnit",
    "PermittivityValue", "PhaseCoefficientUnit", "PhaseCoefficientValue", "PhaseDifferenceUnit",
    "PhaseDifferenceValue", "PhaseSpeedOfElectromagneticWavesUnit",
    "PhaseSpeedOfElectromagneticWavesValue", "PhaseSpeedUnit", "PhaseSpeedValue",
    "PhaseVelocityUnit", "PhaseVelocityValue", "PhotonExitanceUnit", "PhotonExitanceValue",
    "PhotonExposureUnit", "PhotonExposureValue", "PhotonFluxUnit", "PhotonFluxValue",
    "PhotonIntensityUnit", "PhotonIntensityValue", "PhotonIrradianceUnit",
    "PhotonIrradianceValue", "PhotonNumberValue", "PhotonRadianceUnit", "PhotonRadianceValue",
    "PlanckFunctionUnit", "PlanckFunctionValue", "PlaneAngleUnit", "PlaneAngleValue",
    "PlanetaryPosition3dVector", "PlanetarySpatial3dCoordinateFrame", "PoiseuilleNumberValue",
    "PoissonNumberValue", "PomerantsevNumberValue", "Position3dVector", "PowerFactorValue",
    "PowerNumberValue", "PowerUnit", "PowerValue", "PoyntingVectorMagnitudeUnit",
    "PoyntingVectorMagnitudeValue", "PrandtlMagneticNumberValue", "PrandtlNumberValue",
    "PressureCoefficientUnit", "PressureCoefficientValue", "PressureUnit", "PressureValue",
    "PropagationCoefficientUnit", "PropagationCoefficientValue",
    "QualityFactorForIonizingRadiationUnit", "QualityFactorForIonizingRadiationValue",
    "QualityFactorValue", "QuantityOfIlluminationUnit", "QuantityOfIlluminationValue",
    "QuantityOfLightUnit", "QuantityOfLightValue", "QuantumNumberValue", "RadianceFactorValue",
    "RadianceUnit", "RadianceValue", "RadiantEmittanceUnit", "RadiantEmittanceValue",
    "RadiantEnergyDensityUnit", "RadiantEnergyDensityValue", "RadiantExitanceUnit",
    "RadiantExitanceValue", "RadiantExposureUnit", "RadiantExposureValue", "RadiantFluxUnit",
    "RadiantFluxValue", "RadiantIntensityUnit", "RadiantIntensityValue", "RadiantPowerUnit",
    "RadiantPowerValue", "RatioOfSpecificHeatCapacitiesValue", "RayleighNumberValue",
    "ReactanceUnit", "ReactanceValue", "RecombinationCoefficientUnit",
    "RecombinationCoefficientValue", "RedundancyUnit", "RedundancyValue", "ReechNumberValue",
    "ReflectanceFactorValue", "ReflectanceValue", "RefractiveIndexValue",
    "RelativeAtomicMassValue", "RelativeEntropyValue", "RelativeHumidityValue",
    "RelativeLinearStrainValue", "RelativeMassConcentrationOfVapourValue",
    "RelativeMassDefectValue", "RelativeMassDensityValue", "RelativeMassExcessValue",
    "RelativeMassRatioOfVapourValue", "RelativePermeabilityValue", "RelativePermittivityValue",
    "RelativePressureCoefficientUnit", "RelativePressureCoefficientValue",
    "RelativeRedundancyValue", "RelativeVolumeStrainValue", "ReluctanceUnit", "ReluctanceValue",
    "RepetencyUnit", "RepetencyValue", "ResistanceToAlternatingCurrentUnit",
    "ResistanceToAlternatingCurrentValue", "ResistanceUnit", "ResistanceValue",
    "ResistivityUnit", "ResistivityValue", "ResonanceEscapeProbabilityValue",
    "ReynoldsElectricNumberValue", "ReynoldsMagneticNumberValue", "ReynoldsNumberValue",
    "RichardsonConstantUnit", "RichardsonConstantValue", "RichardsonNumberValue",
    "RobertsNumberValue", "RollingResistanceFactorValue", "RossbyNumberValue",
    "RydbergConstantUnit", "RydbergConstantValue", "SchmidtNumberValue",
    "SecondAxialMomentOfAreaUnit", "SecondAxialMomentOfAreaValue",
    "SecondPolarMomentOfAreaUnit", "SecondPolarMomentOfAreaValue", "SectionModulusUnit",
    "SectionModulusValue", "SeebeckCoefficientForSubstancesAAndBUnit",
    "SeebeckCoefficientForSubstancesAAndBValue", "SelfInductanceUnit", "SelfInductanceValue",
    "ShearModulusUnit", "ShearModulusValue", "ShearStrainValue", "ShearStressUnit",
    "ShearStressValue", "ShortRangeOrderParameterValue", "SlowingDownDensityUnit",
    "SlowingDownDensityValue", "SolidAngularMeasureUnit", "SolidAngularMeasureValue",
    "SommerfeldNumberValue", "SoundEnergyDensityUnit", "SoundEnergyDensityValue",
    "SoundExposureLevelUnit", "SoundExposureLevelValue", "SoundExposureUnit",
    "SoundExposureValue", "SoundIntensityUnit", "SoundIntensityValue", "SoundPowerLevelUnit",
    "SoundPowerLevelValue", "SoundPressureLevelUnit", "SoundPressureLevelValue",
    "SourceTensionUnit", "SourceTensionValue", "SourceVoltageUnit", "SourceVoltageValue",
    "Spatial3dCoordinateFrame", "SpecificActivityUnit", "SpecificActivityValue",
    "SpecificEnergyUnit", "SpecificEnergyValue", "SpecificEnthalpyUnit",
    "SpecificEnthalpyValue", "SpecificEntropyUnit", "SpecificEntropyValue",
    "SpecificGasConstantUnit", "SpecificGasConstantValue",
    "SpecificHeatCapacityAtConstantPressureUnit", "SpecificHeatCapacityAtConstantPressureValue",
    "SpecificHeatCapacityAtConstantVolumeUnit", "SpecificHeatCapacityAtConstantVolumeValue",
    "SpecificHeatCapacityAtSaturatedVapourPressureUnit",
    "SpecificHeatCapacityAtSaturatedVapourPressureValue", "SpecificHeatCapacityUnit",
    "SpecificHeatCapacityValue", "SpecificOpticalRotatoryPowerUnit",
    "SpecificOpticalRotatoryPowerValue", "SpecificVolumeUnit", "SpecificVolumeValue",
    "SpectralIrradianceUnit", "SpectralIrradianceValue", "SpectralLuminousEfficacyUnit",
    "SpectralLuminousEfficacyValue", "SpectralLuminousEfficiencyValue", "SpectralRadianceUnit",
    "SpectralRadianceValue", "SpectralRadiantEnergyDensityInTermsOfWavelengthUnit",
    "SpectralRadiantEnergyDensityInTermsOfWavelengthValue",
    "SpectralRadiantEnergyDensityInTermsOfWavenumberUnit",
    "SpectralRadiantEnergyDensityInTermsOfWavenumberValue", "SpectralRadiantEnergyUnit",
    "SpectralRadiantEnergyValue", "SpectralRadiantExitanceUnit", "SpectralRadiantExitanceValue",
    "SpectralRadiantExposureUnit", "SpectralRadiantExposureValue", "SpectralRadiantFluxUnit",
    "SpectralRadiantFluxValue", "SpectralRadiantIntensityUnit", "SpectralRadiantIntensityValue",
    "SpectralRadiantPowerUnit", "SpectralRadiantPowerValue", "SpeedOfLightInAMediumUnit",
    "SpeedOfLightInAMediumValue", "SpeedOfLightUnit", "SpeedOfLightValue", "SpeedUnit",
    "SpeedValue", "SphericalDisplacement3dVector", "SphericalPosition3dVector",
    "SphericalSpatial3dCoordinateFrame", "SpinUnit", "SpinValue",
    "StandardAbsoluteActivityInMixtureValue", "StandardAbsoluteActivityInSolutionValue",
    "StandardAbsoluteActivityOfSolventValue", "StandardChemicalPotentialUnit",
    "StandardChemicalPotentialValue", "StandardEquilibriumConstantValue",
    "StantonNumberForMassTransferValue", "StantonNumberValue", "StarkNumberValue",
    "StaticFrictionCoefficientValue", "StefanNumberValue",
    "StoichiometricNumberOfSubstanceValue", "StokesNumberForDragValue",
    "StokesNumberForGravityValue", "StokesNumberForRotameterValue",
    "StokesNumberForVibratingParticlesValue", "StokesNumberValue", "StorageCapacityUnit",
    "StorageCapacityValue", "StorageSizeUnit", "StorageSizeValue", "StrainUnit", "StrainValue",
    "StressUnit", "StressValue", "StrouhalNumberValue", "StructureFactorValue",
    "StuartElectricalNumberValue", "StuartNumberValue", "SurfaceActivityDensityUnit",
    "SurfaceActivityDensityValue", "SurfaceCoefficientOfHeatTransferUnit",
    "SurfaceCoefficientOfHeatTransferValue", "SurfaceDensityOfElectricChargeUnit",
    "SurfaceDensityOfElectricChargeValue", "SurfaceDensityUnit", "SurfaceDensityValue",
    "SurfaceMassDensityUnit", "SurfaceMassDensityValue", "SurfaceTensionUnit",
    "SurfaceTensionValue", "SusceptanceUnit", "SusceptanceValue", "TaylorNumberValue",
    "TemperatureDifferenceUnit", "TemperatureDifferenceValue", "TemperatureUnit",
    "TemperatureValue", "ThermalConductanceUnit", "ThermalConductanceValue",
    "ThermalConductivityUnit", "ThermalConductivityValue", "ThermalDiffusionCoefficientUnit",
    "ThermalDiffusionCoefficientValue", "ThermalDiffusionFactorValue",
    "ThermalDiffusionRatioValue", "ThermalDiffusivityUnit", "ThermalDiffusivityValue",
    "ThermalEfficiencyValue", "ThermalInsulanceUnit", "ThermalInsulanceValue",
    "ThermalResistanceUnit", "ThermalResistanceValue", "ThermalUtilizationFactorUnit",
    "ThermalUtilizationFactorValue", "ThermodynamicTemperatureUnit",
    "ThermodynamicTemperatureValue", "ThomsonCoefficientUnit", "ThomsonCoefficientValue",
    "ThrustCoefficientValue", "TimeUnit", "TimeValue", "TorqueUnit", "TorqueValue",
    "TotalAngularMomentumUnit", "TotalAngularMomentumValue", "TotalCurrentDensityUnit",
    "TotalCurrentDensityValue", "TotalIonizationValue", "TotalLinearStoppingPowerUnit",
    "TotalLinearStoppingPowerValue", "TotalMassStoppingPowerUnit",
    "TotalMassStoppingPowerValue", "TrafficCarriedIntensityUnit",
    "TrafficCarriedIntensityValue", "TrafficIntensityUnit", "TrafficIntensityValue",
    "TrafficLoadUnit", "TrafficLoadValue", "TrafficOfferedIntensityUnit",
    "TrafficOfferedIntensityValue", "TransferRateUnit", "TransferRateValue",
    "TransinformationContentUnit", "TransinformationContentValue",
    "TransmittanceOpticalDensityValue", "TransmittanceValue", "TransportNumberOfTheIonBValue",
    "TristimulusValuesForTheCie1931StandardColorimetricObserverUnit",
    "TristimulusValuesForTheCie1931StandardColorimetricObserverValue",
    "TristimulusValuesForTheCie1964StandardColorimetricObserverUnit",
    "TristimulusValuesForTheCie1964StandardColorimetricObserverValue", "ViscosityUnit",
    "ViscosityValue", "VolumeFlowRateUnit", "VolumeFlowRateValue", "VolumeFractionUnit",
    "VolumeFractionValue", "VolumeUnit", "VolumeValue", "VolumicActivityUnit",
    "VolumicActivityValue", "VolumicCrossSectionUnit", "VolumicCrossSectionValue",
    "VolumicElectricChargeUnit", "VolumicElectricChargeValue",
    "VolumicElectromagneticEnergyUnit", "VolumicElectromagneticEnergyValue",
    "VolumicTotalCrossSectionUnit", "VolumicTotalCrossSectionValue", "WaitingProbabilityValue",
    "WavenumberUnit", "WavenumberValue", "WeberNumberValue", "WeissenbergNumberValue",
    "WomersleyNumberValue", "YoungModulusUnit", "YoungModulusValue", "absoluteActivity",
    "absorbedDose", "absorbedDoseRate", "absorptance", "absorptionNumber", "acceleration",
    "acceptorDensity", "acousticImpedance", "actionQuantity", "activeEnergy", "activePower",
    "activityCoefficient", "activityConcentration", "activityDensity", "activityFactor",
    "activityOfSolute", "activityOfSolvent", "admittance", "aeroelasticityParameter",
    "affinityOfAChemicalReaction", "alphaDisintegrationEnergy", "altitude", "amountOfHeat",
    "amountOfSubstance", "amountOfSubstanceConcentration",
    "amountOfSubstanceFractionMoleFraction", "angleOfOpticalRotation", "angularAcceleration",
    "angularDisplacement", "angularFrequency", "angularImpulse", "angularMeasure",
    "angularMomentum", "angularReciprocalLatticeVectorMagnitude", "angularRepetency",
    "angularVelocity", "angularWavenumber", "apparentPower", "arcLength", "archimedesNumber",
    "area", "areicElectricCharge", "arrheniusNumber", "atomicAttenuationCoefficient",
    "atomicMass", "atomicNumber", "atomicScatteringFactor", "attenuation", "atwoodNumber",
    "averageConditionalInformationContent", "averageEnergyLossPerElementaryChargeProduced",
    "averageInformationRate", "averageLogarithmicEnergyDecrement",
    "averageTransinformationRate", "bagnoldNumber", "bagnoldNumberForSolidParticles",
    "batchelorNumber", "bejanNumber", "bejanNumberForEntropy", "bejanNumberForHeatTransfer",
    "bejanNumberForMassTransfer", "betaDisintegrationEnergy", "binaryDigitRate",
    "bindingFraction", "binghamNumber", "biotNumber", "biotNumberForMassTransfer", "bitPeriod",
    "bitRate", "blakeNumber", "bodensteinNumber", "bohrMagneton", "bohrRadius",
    "boltzmannNumber", "bondNumber", "braggAngle", "breadth", "brinkmanNumber", "bulkModulus",
    "callIntensity", "callingRate", "canonicalPartitionFunction", "capacitance",
    "capillaryNumber", "carnotNumber", "carrierLifetime", "carrierPower",
    "cartesianAcceleration3dVector", "cartesianAngularAcceleration3dVector",
    "cartesianAngularImpulse3dVector", "cartesianAngularMomentum3dVector",
    "cartesianAngularReciprocalLattice3dVector", "cartesianAngularVelocity3dVector",
    "cartesianAreicElectricCurrent3dVector", "cartesianBurgers3dVector",
    "cartesianDisplacement3dVector", "cartesianDisplacementCurrentDensity3dVector",
    "cartesianDragForce3dVector", "cartesianDynamicFrictionForce3dVector",
    "cartesianElectricCurrentDensity3dVector", "cartesianElectricDipoleMoment3dVector",
    "cartesianElectricDisplacement3dVector", "cartesianElectricFieldStrength3dVector",
    "cartesianElectricFluxDensity3dVector", "cartesianElectricPolarization3dVector",
    "cartesianEquilibriumPosition3dVector", "cartesianForce3dVector",
    "cartesianFundamentalLattice3dVector", "cartesianFundamentalReciprocalLattice3dVector",
    "cartesianImpulse3dVector", "cartesianKineticFrictionForce3dVector",
    "cartesianLattice3dVector", "cartesianLinearElectricCurrentDensity3dVector",
    "cartesianLineicElectricCurrent3dVector", "cartesianMagneticAreaMoment3dVector",
    "cartesianMagneticDipoleMoment3dVector", "cartesianMagneticFieldStrength3dVector",
    "cartesianMagneticFluxDensity3dVector", "cartesianMagneticMoment3dVector",
    "cartesianMagneticPolarization3dVector", "cartesianMagneticVectorPotential3dVector",
    "cartesianMagnetization3dVector", "cartesianMagnetizingField3dVector",
    "cartesianMassFlow3dVector", "cartesianMomentOfForce3dVector", "cartesianMomentum3dVector",
    "cartesianParticleCurrentDensity3dVector", "cartesianParticlePosition3dVector",
    "cartesianPosition3dVector", "cartesianPoynting3dVector", "cartesianRollingDrag3dVector",
    "cartesianRollingFrictionForce3dVector", "cartesianRollingResistance3dVector",
    "cartesianSoundIntensity3dVector", "cartesianSoundParticleAcceleration3dVector",
    "cartesianSoundParticleDisplacement3dVector", "cartesianSoundParticleVelocity3dVector",
    "cartesianSpin3dVector", "cartesianStaticFriction3dVector",
    "cartesianStaticFrictionForce3dVector", "cartesianTotalAngularMomentum3dVector",
    "cartesianTotalCurrentDensity3dVector", "cartesianVelocity3dVector",
    "cartesianWave3dVector", "cartesianWeight3dVector", "cauchyNumber", "cavitationNumber",
    "celsiusTemperature", "chandrasekharNumber", "channelCapacity",
    "channelCapacityPerCharacter", "channelTimeCapacity", "characterMeanEntropy",
    "characterMeanTransinformationContent",
    "characteristicImpedanceOfAMediumForLongitudinalWaves", "chargeNumber", "chemicalPotential",
    "chromaticityCoordinatesInTheCie1931StandardColorimetricSystem",
    "chromaticityCoordinatesInTheCie1964StandardColorimetricSystem",
    "cieColourMatchingFunctionsForTheCie1931StandardColorimetricObserver",
    "cieColourMatchingFunctionsForTheCie1964StandardColorimetricObserver", "clausiusNumber",
    "clockFrequency", "clockRate", "coefficientOfHeatTransfer", "coefficientOfStaticFriction",
    "coefficientOfThermalInsulance", "coercivity", "coherenceLength", "colburnNumber",
    "colourTemperature", "completedCallIntensity", "complexAdmittance", "complexImpedance",
    "complexPower", "compressibility", "compressibilityNumber", "comptonWavelength",
    "conditionalEntropy", "conditionalInformationContent", "conductance",
    "conductanceForAlternatingCurrent", "conductivity", "correlatedColourTemperature",
    "couplingFactor", "cowlingNumber", "crossSection", "cubicExpansionCoefficient",
    "curieTemperature", "currentFractionOfTheIonB", "currentLinkage", "curvature",
    "cyclotronAngularFrequency", "cylindricalDisplacement3dVector",
    "cylindricalPosition3dVector", "dampingCoefficient", "darcyFrictionFactor", "deanNumber",
    "deborahNumber", "debyeAngularFrequency", "debyeAngularRepetency", "debyeAngularWavenumber",
    "debyeTemperature", "debyeWallerFactor", "decadicAbsorbance", "decayConstant",
    "decisionContent", "degeneracy", "degreeOfDissociation", "density", "densityOfHeatFlowRate",
    "densityOfVibrationalStates", "depth", "dewPointTemperature", "diameter", "diffusionArea",
    "diffusionCoefficient", "diffusionCoefficientForFluenceRate",
    "diffusionCoefficientForParticleNumberDensity", "diffusionLength",
    "diffusionLengthForCondensedMatterPhysics", "directionAndEnergyDistributionOfCrossSection",
    "directionDistributionOfCrossSection", "disintegrationConstant", "displacement3dVector",
    "displacementCurrent", "displacementCurrentDensity", "dissociationFraction", "distance",
    "donorDensity", "doseEquivalent", "doseEquivalentRate", "dragCoefficient", "dragFactor",
    "dulongNumber", "duration", "dynamicCapillaryNumber", "dynamicFrictionFactor",
    "dynamicViscosity", "eckertNumber", "effectiveMass", "ekmanNumber", "elasticityNumber",
    "electricCharge", "electricChargeDensity", "electricConstant", "electricCurrent",
    "electricCurrentDensity", "electricCurrentPhasor", "electricDipoleMoment",
    "electricFieldParameter", "electricFieldStrength", "electricFlux", "electricFluxDensity",
    "electricPolarization", "electricPotential", "electricPotentialDifference", "electricPower",
    "electricSusceptibility", "electricTension", "electrolyticConductivity",
    "electromagneticEnergyDensity", "electronAffinity", "electronDensity", "electronRadius",
    "elementaryCharge", "emissivity", "emissivityAtASpecifiedWavelength", "energy",
    "energyDensityOfStates", "energyDistributionOfCrossSection", "energyFluence",
    "energyFluenceRate", "energyImparted", "enthalpy", "enthalpyOfPhaseTransition", "entropy",
    "entropyForInformationScience", "equilibriumConstantOnConcentrationBasis",
    "equilibriumConstantOnPressureBasis", "equivalentBinaryDigitRate",
    "equivalentBinaryStorageCapacity", "equivalentBitRate", "equivocation", "errorProbability",
    "eulerMagneticNumber", "eulerNumber", "exchangeIntegral", "expansionNumber", "exposure",
    "exposureRate", "extentOfReaction", "extinction", "fanningNumber", "fastFissionFactor",
    "fermiAngularRepetency", "fermiAngularWavenumber", "fermiEnergy", "fermiTemperature",
    "force", "fourierNumber", "fourierNumberForMassTransfer", "frequency", "froudeNumber",
    "froudeNumberForHeatTransfer", "fugacity", "fundamentalReciprocalLatticeVectorMagnitude",
    "gFactorOfAtom", "gFactorOfNucleusOrNuclearParticle", "galileiNumber", "gapEnergy",
    "gaugePressure", "gibbsEnergy", "gibbsFunction", "goertlerNumber", "goertlerParameter",
    "graetzNumber", "graetzNumberForMassTransfer", "grandCanonicalPartitionFunction",
    "grandPartitionFunction", "grashofMagneticNumber", "grashofNumber",
    "grashofNumberForMassTransfer", "groupSpeed", "groupVelocity", "gyromagneticCoefficient",
    "gyromagneticCoefficientOfTheElectron", "gyromagneticRatio",
    "gyromagneticRatioOfTheElectron", "gyroradius", "hagenNumber", "halfLife",
    "halfValueThickness", "hallCoefficient", "hallNumber", "hammingDistance", "hartmannNumber",
    "hartreeEnergy", "heat", "heatCapacity", "heatFlowRate", "heatTransferFactor",
    "heatTransferNumber", "height", "helmholtzEnergy", "helmholtzFunction", "holeDensity",
    "hookeNumber", "hyperfineStructureQuantumNumber", "illuminance", "impedance", "impulse",
    "inductance", "infiniteMultiplicationFactor", "informationContent", "instantaneousPower",
    "internalConversionFactor", "internalEnergy", "intrinsicCarrierDensity", "ionDensity",
    "ionNumberDensity", "ionicStrength", "ionizationEnergy", "ionizationNumber", "irradiance",
    "irrelevance", "isentropicCompressibility", "isentropicExpansionFactor",
    "isentropicExponent", "isothermalCompressibility", "isq", "jFactor",
    "jointInformationContent", "jouleMagneticNumber", "jouleThomsonCoefficient", "kerma",
    "kermaRate", "kiebelNumber", "kinematicViscosity", "kineticEnergy", "kineticFrictionFactor",
    "knudsenNumber", "lagrangeNumber", "landauGinzburgNumber", "landeFactor", "laplaceNumber",
    "larmorAngularFrequency", "larmorFrequency", "larmorRadius", "latentHeat",
    "latentHeatOfPhaseTransition", "latticePlaneSpacing", "lavalNumber", "leakageFactor",
    "length", "lethargy", "levelWidth", "lewisNumber", "liftCoefficient", "lightExposure",
    "lightSpeed", "lineDigitRate", "linearAbsorptionCoefficient",
    "linearAttenuationCoefficient", "linearAttenuationCoefficientForIonizingRadiation",
    "linearDensity", "linearDensityOfElectricCharge", "linearElectricCurrentDensity",
    "linearEnergyTransfer", "linearExpansionCoefficient", "linearExtinctionCoefficient",
    "linearIonization", "linearMassDensity", "linearStoppingPower", "lineicElectricCharge",
    "linkedFlux", "lockhartMartinelliParameter", "logarithmicDecrement",
    "logarithmicFrequencyRange", "londonPenetrationDepth", "longRangeOrderParameter",
    "lorentzNumber", "lorenzCoefficient", "lossAngle", "lossFactor", "lossProbability",
    "lowerCriticalMagneticFluxDensity", "luminance", "luminanceFactor", "luminousAbsorptance",
    "luminousEfficacyOfASource", "luminousEfficacyOfRadiation", "luminousEfficiency",
    "luminousEnergy", "luminousExitance", "luminousExposure", "luminousFlux",
    "luminousIntensity", "luminousReflectance", "luminousTransmittance", "lundquistNumber",
    "machMagneticNumber", "machNumber", "macroscopicCrossSection",
    "macroscopicTotalCrossSection", "magneticConstant", "magneticDipoleMoment",
    "magneticFieldStrength", "magneticFlux", "magneticFluxDensity", "magneticMoment",
    "magneticNumber", "magneticPolarization", "magneticPressureNumber", "magneticQuantumNumber",
    "magneticSusceptibility", "magneticTension", "magneticVectorPotential", "magnetization",
    "magnetogyricRatio", "magnetogyricRatioOfTheElectron", "magnetomotiveForce",
    "marangoniNumber", "mass", "massAbsorptionCoefficient", "massAttenuationCoefficient",
    "massAttenuationCoefficientForIonizingRadiation", "massChangeRate", "massConcentration",
    "massConcentrationOfWater", "massConcentrationOfWaterVapourAbsoluteHumidity", "massDefect",
    "massDensity", "massEnergyTransferCoefficient", "massExcess", "massFlow", "massFlowRate",
    "massFraction", "massFractionOfDryMatter", "massFractionOfWater", "massNumber",
    "massRatioOfWaterToDryMatter", "massRatioOfWaterVapourToDryGas", "massStoppingPower",
    "massTransferFactor", "massicActivity", "massieuFunction", "maximumBetaParticleEnergy",
    "maximumEntropy", "maximumLuminousEfficacy", "maximumThermalEfficiency",
    "meanConditionalInformationContent", "meanDurationOfLife", "meanEnergyImparted",
    "meanFreePath", "meanFreePathForAtomicPhysics", "meanFreePathOfElectrons",
    "meanFreePathOfPhonons", "meanLifeTime", "meanLinearRange", "meanMassRange",
    "meanQueueLength", "meanTransinformationContent", "mechanicalEfficiency",
    "mechanicalEnergy", "mechanicalPower", "mechanicalWork", "microcanonicalPartitionFunction",
    "migrationArea", "migrationLength", "mobility", "mobilityRatio", "modulationRate",
    "modulusOfAdmittance", "modulusOfCompression", "modulusOfElasticity", "modulusOfImpedance",
    "modulusOfRigidity", "molality", "molarAbsorptionCoefficient",
    "molarAttenuationCoefficient", "molarConductivity", "molarEnthalpy", "molarEntropy",
    "molarGasConstant", "molarGibbsEnergy", "molarHeatCapacity", "molarHelmholtzEnergy",
    "molarInternalEnergy", "molarMass", "molarOpticalRotatoryPower", "molarVolume",
    "molecularConcentration", "molecularPartitionFunction", "momentOfForce", "momentOfInertia",
    "momentOfInertiaTensor", "momentum", "moodyFrictionFactor", "mortonNumber",
    "multiplicationFactor", "multiplicity", "mutualInductance", "napierianAbsorbance",
    "nazeNumber", "neutronNumber", "neutronYieldPerAbsorption", "neutronYieldPerFission",
    "nonActivePower", "nonLeakageProbability", "normalStress", "nuclearActivity",
    "nuclearMagneton", "nuclearPrecessionAngularFrequency", "nuclearQuadrupoleMoment",
    "nuclearRadius", "nuclearSpinQuantumNumber", "nucleonNumber", "nuclidicMass",
    "numberOfEntities", "numberOfMoles", "numberOfPhotons", "numberOfTurnsInAWinding",
    "nusseltElectricNumber", "nusseltNumber", "nusseltNumberForMassTransfer", "ohnesorgeNumber",
    "opticalDensity", "orbitalAngularMomentumQuantumNumber", "osmoticCoefficientOfSolventA",
    "osmoticFactorOfSolvent", "osmoticPressure", "packingFraction", "partialPressure",
    "particleConcentration", "particleCurrentDensity", "particleEmissionRate",
    "particleFluence", "particleFluenceRate", "particleNumberDensity", "particleSourceDensity",
    "partitionFunctionOfAMolecule", "pathLength", "peltierCoefficientForSubstancesAAndB",
    "period", "periodDuration", "periodOfBinaryDigits", "periodOfDataElements", "permeability",
    "permeabilityOfVacuum", "permeance", "permittivity", "permittivityOfVacuum", "phaseAngle",
    "phaseCoefficient", "phaseDifference", "phaseSpeed", "phaseSpeedOfElectromagneticWaves",
    "phaseVelocity", "photonEnergy", "photonExitance", "photonExposure", "photonFlux",
    "photonIntensity", "photonIrradiance", "photonNumber", "photonRadiance", "planckFunction",
    "planeAngle", "planetaryPosition3dVector", "plasticityNumber", "poiseuilleNumber",
    "poissonNumber", "pomerantsevNumber", "position3dVector", "potentialEnergy", "power",
    "powerCoefficient", "powerFactor", "powerNumber", "poyntingVectorMagnitude",
    "prandtlMagneticNumber", "prandtlNumber", "pressure", "pressureCoefficient",
    "principalQuantumNumber", "propagationCoefficient", "properMass", "protonNumber",
    "qualityFactor", "qualityFactorForIonizingRadiation", "quantityOfIllumination",
    "quantityOfLight", "quantizingDistortionRate", "quantumNumber", "radialDistance",
    "radiance", "radianceFactor", "radiantEmittance", "radiantEnergy", "radiantEnergyDensity",
    "radiantEnergyForIonizingRadiation", "radiantExitance", "radiantExposure", "radiantFlux",
    "radiantIntensity", "radiantPower", "radius", "radiusOfCurvature",
    "ratioOfSpecificHeatCapacities", "rayleighNumber", "reactance", "reactionEnergy",
    "reactivePower", "reactorTimeConstant", "recombinationCoefficient", "redundancy",
    "reechNumber", "reflectance", "reflectanceFactor", "refractiveIndex",
    "relativeActivityOfSolute", "relativeActivityOfSolvent", "relativeAtomicMass",
    "relativeDensity", "relativeEntropy", "relativeHumidity", "relativeLinearStrain",
    "relativeMassConcentrationOfVapour", "relativeMassDefect", "relativeMassDensity",
    "relativeMassExcess", "relativeMassRatioOfVapour", "relativePermeability",
    "relativePermittivity", "relativePressureCoefficient", "relativeRedundancy",
    "relativeVolumeStrain", "relaxationTime", "reluctance", "repetency", "residualResistivity",
    "resistance", "resistanceToAlternatingCurrent", "resistivity", "resonanceEnergy",
    "resonanceEscapeProbability", "restEnergy", "restMass", "reverberationTime",
    "reynoldsElectricNumber", "reynoldsMagneticNumber", "reynoldsNumber", "richardsonConstant",
    "richardsonNumber", "robertsNumber", "rollingResistanceFactor", "rossbyNumber", "rotation",
    "rotationalDisplacement", "rotationalFrequency", "rydbergConstant",
    "scalarMagneticPotential", "schmidtNumber", "secondAxialMomentOfArea",
    "secondPolarMomentOfArea", "sectionModulus", "seebeckCoefficientForSubstancesAAndB",
    "selfInductance", "shearModulus", "shearStrain", "shearStress", "shortRangeOrderParameter",
    "signalEnergyPerBinaryDigit", "slowingDownArea", "slowingDownDensity", "slowingDownLength",
    "solidAngularMeasure", "sommerfeldNumber", "soundEnergy", "soundEnergyDensity",
    "soundExposure", "soundExposureLevel", "soundIntensity", "soundPower", "soundPowerLevel",
    "soundPressure", "soundPressureLevel", "sourceTension", "sourceVoltage", "specificActivity",
    "specificEnergy", "specificEnergyImparted", "specificEnthalpy", "specificEntropy",
    "specificGasConstant", "specificGibbsEnergy", "specificGibbsFunction",
    "specificHeatCapacity", "specificHeatCapacityAtConstantPressure",
    "specificHeatCapacityAtConstantVolume", "specificHeatCapacityAtSaturatedVapourPressure",
    "specificHelmholtzEnergy", "specificHelmholtzFunction", "specificInternalEnergy",
    "specificOpticalRotatoryPower", "specificThermodynamicEnergy", "specificVolume",
    "spectralIrradiance", "spectralLuminousEfficacy", "spectralLuminousEfficiency",
    "spectralRadiance", "spectralRadiantEnergy",
    "spectralRadiantEnergyDensityInTermsOfWavelength",
    "spectralRadiantEnergyDensityInTermsOfWavenumber", "spectralRadiantExitance",
    "spectralRadiantExposure", "spectralRadiantFlux", "spectralRadiantIntensity",
    "spectralRadiantPower", "speed", "speedOfLight", "speedOfLightInAMedium",
    "sphericalDisplacement3dVector", "sphericalPosition3dVector", "spin", "spinQuantumNumber",
    "standardAbsoluteActivityInMixture", "standardAbsoluteActivityInSolution",
    "standardAbsoluteActivityOfSolvent", "standardAmountOfSubstanceConcentration",
    "standardChemicalPotential", "standardEquilibriumConstant", "stantonNumber",
    "stantonNumberForMassTransfer", "starkNumber", "staticFrictionCoefficient",
    "staticFrictionFactor", "staticPressure", "statisticalWeightOfSubsystem", "stefanNumber",
    "stoichiometricNumberOfSubstance", "stokesNumber", "stokesNumberForDrag",
    "stokesNumberForGravity", "stokesNumberForRotameter", "stokesNumberForVibratingParticles",
    "storageCapacity", "storageSize", "strain", "strainTensor", "stress", "stressTensor",
    "strouhalNumber", "structureFactor", "stuartElectricalNumber", "stuartNumber",
    "superconductionTransitionTemperature", "superconductorEnergyGap", "suratmanNumber",
    "surfaceActivityDensity", "surfaceCoefficientOfHeatTransfer", "surfaceDensity",
    "surfaceDensityOfElectricCharge", "surfaceMassDensity", "surfaceTension", "susceptance",
    "taylorNumber", "temperature", "temperatureDifference", "thermalConductance",
    "thermalConductivity", "thermalDiffusionCoefficient", "thermalDiffusionFactor",
    "thermalDiffusionRatio", "thermalDiffusivity", "thermalEfficiency", "thermalInsulance",
    "thermalResistance", "thermalUtilizationFactor", "thermodynamicCriticalMagneticFluxDensity",
    "thermodynamicEnergy", "thermodynamicEquilibriumConstant", "thermodynamicTemperature",
    "thermoelectricVoltageBetweenSubstancesAAndB", "thickness", "thomsonCoefficient",
    "thomsonNumber", "thrustCoefficient", "time", "timeConstant", "torque",
    "totalAngularMomentum", "totalAngularMomentumQuantumNumber", "totalCrossSection",
    "totalCurrent", "totalCurrentDensity", "totalIonization", "totalLinearStoppingPower",
    "totalMassStoppingPower", "trafficCarriedIntensity", "trafficIntensity", "trafficLoad",
    "trafficOfferedIntensity", "transferRate", "transinformationContent", "transmittance",
    "transmittanceDensity", "transmittanceOpticalDensity", "transportNumberOfTheIonB",
    "tristimulusValuesForTheCie1931StandardColorimetricObserver",
    "tristimulusValuesForTheCie1964StandardColorimetricObserver", "unifiedAtomicMassConstant",
    "universalCartesianSpatial3dCoordinateFrame", "upperCriticalMagneticFluxDensity",
    "viscosity", "voltage", "voltagePhasor", "volume", "volumeFlowRate", "volumeFraction",
    "volumeVelocity", "volumicActivity", "volumicCrossSection", "volumicElectricCharge",
    "volumicElectromagneticEnergy", "volumicTotalCrossSection", "waitingProbability",
    "wavelength", "wavenumber", "weberNumber", "weissenbergNumber", "width", "womersleyNumber",
    "work", "workFunction", "youngModulus",
];

pub const SI_NAMES: &[&str] = &[
    "A", "B", "Bd", "Bq", "C", "Da", "E", "F", "GJ", "Gy", "H", "Hart", "Hz", "J", "K", "L",
    "MJ", "N", "Pa", "S", "Sh", "Sv", "T", "V", "W", "Wb", "ampere", "arcmin", "arcsec", "b",
    "barn", "baud", "becquerel", "bit", "byte", "candela", "cd", "centimetre", "cm", "coulomb",
    "d", "dB", "dalton", "day", "dec", "decade", "decibel", "degree", "eV", "electronvolt",
    "erlang", "farad", "g", "gigajoule", "gram", "gray", "h", "hartley", "henry", "hertz",
    "hour", "joule", "kJ", "kW", "kelvin", "kg", "kilogram", "kilojoule", "kilometre",
    "kilowatt", "km", "litre", "lm", "lumen", "lux", "lx", "m", "mL", "mN", "megajoule",
    "metre", "millilitre", "millimetre", "millinewton", "min", "minute", "mm", "mol", "mole",
    "nanometre", "nat", "newton", "nm", "o", "oct", "octave", "octet", "ohm", "pascal", "rad",
    "radian", "s", "second", "shannon", "si", "siemens", "sievert", "sr", "steradian", "tesla",
    "tonne", "u", "ua", "var", "volt", "watt", "weber",
];

pub const SI_PREFIX_NAMES: &[&str] = &[
    "atto", "centi", "deca", "deci", "exa", "exbi", "femto", "gibi", "giga", "hecto", "kibi",
    "kilo", "mebi", "mega", "micro", "milli", "nano", "pebi", "peta", "pico", "tebi", "tera",
    "yobi", "yocto", "yotta", "zebi", "zepto", "zetta",
];

pub const US_CUSTOMARY_NAMES: &[&str] = &[
    "AT", "Btu", "Btu_IT", "Btu_mean", "Btu_th", "NM", "bbl", "bu", "ch", "drypt", "dryqt",
    "floz", "ft", "ftH2O", "ftHg", "gal", "gi", "gr", "hp", "inH2O", "inHg", "kip", "knot",
    "lb", "lbf", "liqpt", "liqqt", "mi", "mil", "mph", "nmi", "oz", "ozf", "pica", "pk", "psi",
    "pt", "rd", "slug", "yd",
];

